use crate::{ffi, MediaType};

#[allow(non_camel_case_types)]
#[derive(Eq, PartialEq, Clone, Copy, Debug, Hash)]
pub enum CodecId {
    None,

    // Video codecs
    MPEG1VIDEO,
    MPEG2VIDEO,
    H261,
    H263,
    RV10,
    RV20,
    MJPEG,
    MJPEGB,
    LJPEG,
    SP5X,
    JPEGLS,
    MPEG4,
    RAWVIDEO,
    MSMPEG4V1,
    MSMPEG4V2,
    MSMPEG4V3,
    WMV1,
    WMV2,
    H263P,
    H263I,
    FLV1,
    SVQ1,
    SVQ3,
    DVVIDEO,
    HUFFYUV,
    CYUV,
    H264,
    INDEO3,
    VP3,
    THEORA,
    ASV1,
    ASV2,
    FFV1,
    XM4,
    VCR1,
    CLJR,
    MDEC,
    ROQ,
    INTERPLAY_VIDEO,
    XAN_WC3,
    XAN_WC4,
    RPZA,
    CINEPAK,
    WS_VQA,
    MSRLE,
    MSVIDEO1,
    IDCIN,
    BPS8,
    SMC,
    FLIC,
    TRUEMOTION1,
    VMDVIDEO,
    MSZH,
    ZLIB,
    QTRLE,
    TSCC,
    ULTI,
    QDRAW,
    VIXL,
    QPEG,
    PNG,
    PPM,
    PBM,
    PGM,
    PGMYUV,
    PAM,
    FFVHUFF,
    RV30,
    RV40,
    VC1,
    WMV3,
    LOCO,
    WNV1,
    AASC,
    INDEO2,
    FRAPS,
    TRUEMOTION2,
    BMP,
    CSCD,
    MMVIDEO,
    ZMBV,
    AVS,
    SMACKVIDEO,
    NUV,
    KMVC,
    FLASHSV,
    CAVS,
    JPEG2000,
    VMNC,
    VP5,
    VP6,
    VP6F,
    TARGA,
    DSICINVIDEO,
    TIERTEXSEQVIDEO,
    TIFF,
    GIF,
    DXA,
    DNXHD,
    THP,
    SGI,
    C93,
    BETHSOFTVID,
    PTX,
    TXD,
    VP6A,
    AMV,
    VB,
    PCX,
    SUNRAST,
    INDEO4,
    INDEO5,
    MIMIC,
    RL2,
    ESCAPE124,
    DIRAC,
    BFI,
    CMV,
    MOTIONPIXELS,
    TGV,
    TGQ,
    TQI,
    AURA,
    AURA2,
    V210X,
    TMV,
    V210,
    DPX,
    MAD,
    FRWU,
    FLASHSV2,
    CDGRAPHICS,
    R210,
    ANM,
    BINKVIDEO,
    IFF_ILBM,
    IFF_BYTERUN1,
    KGV1,
    YOP,
    VP8,
    PICTOR,
    ANSI,
    A64_MULTI,
    A64_MULTI5,
    R10K,
    MXPEG,
    LAGARITH,
    PRORES,
    JV,
    DFA,
    WMV3IMAGE,
    VC1IMAGE,
    UTVIDEO,
    BMV_VIDEO,
    VBLE,
    DXTORY,
    V410,
    XWD,
    CDXL,
    XBM,
    ZEROCODEC,
    MSS1,
    MSA1,
    TSCC2,
    MTS2,
    CLLC,
    MSS2,
    VP9,
    AIC,
    ESCAPE130,
    G2M,
    WEBP,
    HNM4_VIDEO,
    HEVC,
    H265,
    FIC,
    ALIAS_PIX,
    BRENDER_PIX,
    PAF_VIDEO,
    EXR,
    VP7,
    SANM,
    SGIRLE,
    MVC1,
    MVC2,
    HQX,
    TDSC,
    HQ_HQA,
    HAP,
    DDS,
    DXV,
    SCREENPRESSO,
    RSCC,
    Y41P,
    AVRP,
    V012,
    AVUI,
    TARGA_Y216,
    V308,
    V408,
    YUV4,
    AVRN,
    CPIA,
    XFACE,
    SNOW,
    SMVJPEG,
    APNG,
    DAALA,
    CFHD,
    TRUEMOTION2RT,
    M101,
    MAGICYUV,
    SHEERVIDEO,
    YLC,

    // PCM codecs
    PCM_S16LE,
    PCM_S16BE,
    PCM_U16LE,
    PCM_U16BE,
    PCM_S8,
    PCM_U8,
    PCM_MULAW,
    PCM_ALAW,
    PCM_S32LE,
    PCM_S32BE,
    PCM_U32LE,
    PCM_U32BE,
    PCM_S24LE,
    PCM_S24BE,
    PCM_U24LE,
    PCM_U24BE,
    PCM_S24DAUD,
    PCM_ZORK,
    PCM_S16LE_PLANAR,
    PCM_DVD,
    PCM_F32BE,
    PCM_F32LE,
    PCM_F64BE,
    PCM_F64LE,
    PCM_BLURAY,
    PCM_LXF,
    S302M,
    PCM_S8_PLANAR,
    PCM_S24LE_PLANAR,
    PCM_S32LE_PLANAR,
    PCM_S16BE_PLANAR,
    PCM_S64LE,
    PCM_S64BE,

    // ADPCM codecs
    ADPCM_IMA_QT,
    ADPCM_IMA_WAV,
    ADPCM_IMA_DK3,
    ADPCM_IMA_DK4,
    ADPCM_IMA_WS,
    ADPCM_IMA_SMJPEG,
    ADPCM_MS,
    ADPCM_4XM,
    ADPCM_XA,
    ADPCM_ADX,
    ADPCM_EA,
    ADPCM_G726,
    ADPCM_CT,
    ADPCM_SWF,
    ADPCM_YAMAHA,
    ADPCM_SBPRO_4,
    ADPCM_SBPRO_3,
    ADPCM_SBPRO_2,
    ADPCM_THP,
    ADPCM_IMA_AMV,
    ADPCM_EA_R1,
    ADPCM_EA_R3,
    ADPCM_EA_R2,
    ADPCM_IMA_EA_SEAD,
    ADPCM_IMA_EA_EACS,
    ADPCM_EA_XAS,
    ADPCM_EA_MAXIS_XA,
    ADPCM_IMA_ISS,
    ADPCM_G722,
    ADPCM_IMA_APC,
    ADPCM_VIMA,
    ADPCM_AFC,
    ADPCM_IMA_OKI,
    ADPCM_DTK,
    ADPCM_IMA_RAD,
    ADPCM_G726LE,
    ADPCM_THP_LE,
    ADPCM_PSX,
    ADPCM_AICA,
    ADPCM_IMA_DAT4,
    ADPCM_MTAF,

    // AMR codecs
    AMR_NB,
    AMR_WB,

    // RealAudio codecs
    RA_144,
    RA_288,

    // DPCM codecs
    ROQ_DPCM,
    INTERPLAY_DPCM,
    XAN_DPCM,
    SOL_DPCM,
    SDX2_DPCM,

    // Audio codecs
    MP2,
    MP3,
    AAC,
    AC3,
    DTS,
    VORBIS,
    DVAUDIO,
    WMAV1,
    WMAV2,
    MACE3,
    MACE6,
    VMDAUDIO,
    FLAC,
    MP3ADU,
    MP3ON4,
    SHORTEN,
    ALAC,
    WESTWOOD_SND1,
    GSM,
    QDM2,
    COOK,
    TRUESPEECH,
    TTA,
    SMACKAUDIO,
    QCELP,
    WAVPACK,
    DSICINAUDIO,
    IMC,
    MUSEPACK7,
    MLP,
    GSM_MS,
    ATRAC3,
    APE,
    NELLYMOSER,
    MUSEPACK8,
    SPEEX,
    WMAVOICE,
    WMAPRO,
    WMALOSSLESS,
    ATRAC3P,
    EAC3,
    SIPR,
    MP1,
    TWINVQ,
    TRUEHD,
    MP4ALS,
    ATRAC1,
    BINKAUDIO_RDFT,
    BINKAUDIO_DCT,
    AAC_LATM,
    QDMC,
    CELT,
    G723_1,
    G729,
    SVX_EXP8,
    SVX_FIB8,
    BMV_AUDIO,
    RALF,
    IAC,
    ILBC,
    OPUS,
    COMFORT_NOISE,
    TAK,
    METASOUND,
    PAF_AUDIO,
    ON2AVC,
    DSS_SP,
    CODEC2,
    FFWAVESYNTH,
    SONIC,
    SONIC_LS,
    EVRC,
    SMV,
    DSD_LSBF,
    DSD_MSBF,
    DSD_LSBF_PLANAR,
    DSD_MSBF_PLANAR,
    _4GV,
    INTERPLAY_ACM,
    XMA1,
    XMA2,
    DST,

    // Subtitle codecs
    DVD_SUBTITLE,
    DVB_SUBTITLE,
    TEXT,
    XSUB,
    SSA,
    MOV_TEXT,
    HDMV_PGS_SUBTITLE,
    DVB_TELETEXT,
    SRT,
    MICRODVD,
    EIA_608,
    JACOSUB,
    SAMI,
    REALTEXT,
    STL,
    SUBVIEWER1,
    SUBVIEWER,
    SUBRIP,
    WEBVTT,
    MPL2,
    VPLAYER,
    PJS,
    ASS,
    HDMV_TEXT_SUBTITLE,

    // other codecs
    TTF,
    SCTE_35,
    BINTEXT,
    XBIN,
    IDF,
    OTF,
    SMPTE_KLV,
    DVD_NAV,
    TIMED_ID3,
    BIN_DATA,
    PROBE,
    MPEG2TS,
    MPEG4SYSTEMS,
    FFMETADATA,
    WRAPPED_AVFRAME,
    PSD,
    PIXLET,
    SPEEDHQ,
    CLEARVIDEO,
    FMVC,
    SCPR,
    XPM,
    AV1,
    PCM_F16LE,
    PCM_F24LE,
    ATRAC3AL,
    ATRAC3PAL,
    BITPACKED,
    MSCC,
    SRGC,
    SVG,
    GDV,
    FITS,
    GREMLIN_DPCM,
    DOLBY_E,
    APTX,
    APTX_HD,
    SBC,
    AVS2,
    IMM4,
    PROSUMER,
    MWSC,
    WCMV,
    RASC,
    PCM_VIDC,
    ATRAC9,
    TTML,
    HYMT,
    ARBC,
    AGM,
    LSCR,
    VP4,
    ADPCM_AGM,
    HCOM,
    ARIB_CAPTION,
    IMM5,
    MVDV,
    MVHA,
    CDTOONS,
    MV30,
    NOTCHLC,
    PFM,
    ADPCM_ARGO,
    ADPCM_IMA_SSI,
    ADPCM_ZORK,
    ADPCM_IMA_APM,
    ADPCM_IMA_ALP,
    ADPCM_IMA_MTF,
    ADPCM_IMA_CUNNING,
    DERF_DPCM,
    ACELP_KELVIN,
    MPEGH_3D_AUDIO,
    SIREN,
    HCA,
    EPG,
    AVS3,
    PGX,
    MSP2,
    VVC,
    MOBICLIP,
    PHOTOCD,
    ARGO,
    CRI,
    IPU,
    SIMBIOSIS_IMX,
    SGA_VIDEO,
    PCM_SGA,
    ADPCM_IMA_MOFLEX,
    FASTAUDIO,
    GEM,
    ADPCM_IMA_ACORN,
    MSNSIREN,
    VBN,
    JPEGXL,
    QOI,
    PHM,
    DFPWM,
    RADIANCE_HDR,
    WBMP,
    MEDIA100,
    VQC,
    ADPCM_XMD,
    WADY_DPCM,
    CBD2_DPCM,
    BONK,
    MISC4,
    APAC,
    FTR,
    WAVARC,
    RKA,
    VNULL,
    ANULL,
    PDV,
    EVC,
    RTV1,
    VMIX,
    AC4,
    SMPTE_2038,
    OSQ,

    LEAD,
    QOA,
}

impl CodecId {
    pub fn name(&self) -> &'static str {
        unsafe {
            let name = std::ffi::CStr::from_ptr(ffi::avcodec_get_name((*self).into()));
            std::str::from_utf8_unchecked(name.to_bytes())
        }
    }

    pub fn medium(&self) -> MediaType {
        unsafe {
            let media_type = ffi::avcodec_get_type((*self).into());
            MediaType::from(media_type)
        }
    }
}

impl From<ffi::AVCodecID> for CodecId {
    fn from(value: ffi::AVCodecID) -> Self {
        use ffi::AVCodecID::*;

        match value {
            AV_CODEC_ID_NONE => CodecId::None,

            // Video codecs
            AV_CODEC_ID_MPEG1VIDEO => CodecId::MPEG1VIDEO,
            AV_CODEC_ID_MPEG2VIDEO => CodecId::MPEG2VIDEO,
            AV_CODEC_ID_H261 => CodecId::H261,
            AV_CODEC_ID_H263 => CodecId::H263,
            AV_CODEC_ID_RV10 => CodecId::RV10,
            AV_CODEC_ID_RV20 => CodecId::RV20,
            AV_CODEC_ID_MJPEG => CodecId::MJPEG,
            AV_CODEC_ID_MJPEGB => CodecId::MJPEGB,
            AV_CODEC_ID_LJPEG => CodecId::LJPEG,
            AV_CODEC_ID_SP5X => CodecId::SP5X,
            AV_CODEC_ID_JPEGLS => CodecId::JPEGLS,
            AV_CODEC_ID_MPEG4 => CodecId::MPEG4,
            AV_CODEC_ID_RAWVIDEO => CodecId::RAWVIDEO,
            AV_CODEC_ID_MSMPEG4V1 => CodecId::MSMPEG4V1,
            AV_CODEC_ID_MSMPEG4V2 => CodecId::MSMPEG4V2,
            AV_CODEC_ID_MSMPEG4V3 => CodecId::MSMPEG4V3,
            AV_CODEC_ID_WMV1 => CodecId::WMV1,
            AV_CODEC_ID_WMV2 => CodecId::WMV2,
            AV_CODEC_ID_H263P => CodecId::H263P,
            AV_CODEC_ID_H263I => CodecId::H263I,
            AV_CODEC_ID_FLV1 => CodecId::FLV1,
            AV_CODEC_ID_SVQ1 => CodecId::SVQ1,
            AV_CODEC_ID_SVQ3 => CodecId::SVQ3,
            AV_CODEC_ID_DVVIDEO => CodecId::DVVIDEO,
            AV_CODEC_ID_HUFFYUV => CodecId::HUFFYUV,
            AV_CODEC_ID_CYUV => CodecId::CYUV,
            AV_CODEC_ID_H264 => CodecId::H264,
            AV_CODEC_ID_INDEO3 => CodecId::INDEO3,
            AV_CODEC_ID_VP3 => CodecId::VP3,
            AV_CODEC_ID_THEORA => CodecId::THEORA,
            AV_CODEC_ID_ASV1 => CodecId::ASV1,
            AV_CODEC_ID_ASV2 => CodecId::ASV2,
            AV_CODEC_ID_FFV1 => CodecId::FFV1,
            AV_CODEC_ID_4XM => CodecId::XM4,
            AV_CODEC_ID_VCR1 => CodecId::VCR1,
            AV_CODEC_ID_CLJR => CodecId::CLJR,
            AV_CODEC_ID_MDEC => CodecId::MDEC,
            AV_CODEC_ID_ROQ => CodecId::ROQ,
            AV_CODEC_ID_INTERPLAY_VIDEO => CodecId::INTERPLAY_VIDEO,
            AV_CODEC_ID_XAN_WC3 => CodecId::XAN_WC3,
            AV_CODEC_ID_XAN_WC4 => CodecId::XAN_WC4,
            AV_CODEC_ID_RPZA => CodecId::RPZA,
            AV_CODEC_ID_CINEPAK => CodecId::CINEPAK,
            AV_CODEC_ID_WS_VQA => CodecId::WS_VQA,
            AV_CODEC_ID_MSRLE => CodecId::MSRLE,
            AV_CODEC_ID_MSVIDEO1 => CodecId::MSVIDEO1,
            AV_CODEC_ID_IDCIN => CodecId::IDCIN,
            AV_CODEC_ID_8BPS => CodecId::BPS8,
            AV_CODEC_ID_SMC => CodecId::SMC,
            AV_CODEC_ID_FLIC => CodecId::FLIC,
            AV_CODEC_ID_TRUEMOTION1 => CodecId::TRUEMOTION1,
            AV_CODEC_ID_VMDVIDEO => CodecId::VMDVIDEO,
            AV_CODEC_ID_MSZH => CodecId::MSZH,
            AV_CODEC_ID_ZLIB => CodecId::ZLIB,
            AV_CODEC_ID_QTRLE => CodecId::QTRLE,
            AV_CODEC_ID_TSCC => CodecId::TSCC,
            AV_CODEC_ID_ULTI => CodecId::ULTI,
            AV_CODEC_ID_QDRAW => CodecId::QDRAW,
            AV_CODEC_ID_VIXL => CodecId::VIXL,
            AV_CODEC_ID_QPEG => CodecId::QPEG,
            AV_CODEC_ID_PNG => CodecId::PNG,
            AV_CODEC_ID_PPM => CodecId::PPM,
            AV_CODEC_ID_PBM => CodecId::PBM,
            AV_CODEC_ID_PGM => CodecId::PGM,
            AV_CODEC_ID_PGMYUV => CodecId::PGMYUV,
            AV_CODEC_ID_PAM => CodecId::PAM,
            AV_CODEC_ID_FFVHUFF => CodecId::FFVHUFF,
            AV_CODEC_ID_RV30 => CodecId::RV30,
            AV_CODEC_ID_RV40 => CodecId::RV40,
            AV_CODEC_ID_VC1 => CodecId::VC1,
            AV_CODEC_ID_WMV3 => CodecId::WMV3,
            AV_CODEC_ID_LOCO => CodecId::LOCO,
            AV_CODEC_ID_WNV1 => CodecId::WNV1,
            AV_CODEC_ID_AASC => CodecId::AASC,
            AV_CODEC_ID_INDEO2 => CodecId::INDEO2,
            AV_CODEC_ID_FRAPS => CodecId::FRAPS,
            AV_CODEC_ID_TRUEMOTION2 => CodecId::TRUEMOTION2,
            AV_CODEC_ID_BMP => CodecId::BMP,
            AV_CODEC_ID_CSCD => CodecId::CSCD,
            AV_CODEC_ID_MMVIDEO => CodecId::MMVIDEO,
            AV_CODEC_ID_ZMBV => CodecId::ZMBV,
            AV_CODEC_ID_AVS => CodecId::AVS,
            AV_CODEC_ID_SMACKVIDEO => CodecId::SMACKVIDEO,
            AV_CODEC_ID_NUV => CodecId::NUV,
            AV_CODEC_ID_KMVC => CodecId::KMVC,
            AV_CODEC_ID_FLASHSV => CodecId::FLASHSV,
            AV_CODEC_ID_CAVS => CodecId::CAVS,
            AV_CODEC_ID_JPEG2000 => CodecId::JPEG2000,
            AV_CODEC_ID_VMNC => CodecId::VMNC,
            AV_CODEC_ID_VP5 => CodecId::VP5,
            AV_CODEC_ID_VP6 => CodecId::VP6,
            AV_CODEC_ID_VP6F => CodecId::VP6F,
            AV_CODEC_ID_TARGA => CodecId::TARGA,
            AV_CODEC_ID_DSICINVIDEO => CodecId::DSICINVIDEO,
            AV_CODEC_ID_TIERTEXSEQVIDEO => CodecId::TIERTEXSEQVIDEO,
            AV_CODEC_ID_TIFF => CodecId::TIFF,
            AV_CODEC_ID_GIF => CodecId::GIF,
            AV_CODEC_ID_DXA => CodecId::DXA,
            AV_CODEC_ID_DNXHD => CodecId::DNXHD,
            AV_CODEC_ID_THP => CodecId::THP,
            AV_CODEC_ID_SGI => CodecId::SGI,
            AV_CODEC_ID_C93 => CodecId::C93,
            AV_CODEC_ID_BETHSOFTVID => CodecId::BETHSOFTVID,
            AV_CODEC_ID_PTX => CodecId::PTX,
            AV_CODEC_ID_TXD => CodecId::TXD,
            AV_CODEC_ID_VP6A => CodecId::VP6A,
            AV_CODEC_ID_AMV => CodecId::AMV,
            AV_CODEC_ID_VB => CodecId::VB,
            AV_CODEC_ID_PCX => CodecId::PCX,
            AV_CODEC_ID_SUNRAST => CodecId::SUNRAST,
            AV_CODEC_ID_INDEO4 => CodecId::INDEO4,
            AV_CODEC_ID_INDEO5 => CodecId::INDEO5,
            AV_CODEC_ID_MIMIC => CodecId::MIMIC,
            AV_CODEC_ID_RL2 => CodecId::RL2,
            AV_CODEC_ID_ESCAPE124 => CodecId::ESCAPE124,
            AV_CODEC_ID_DIRAC => CodecId::DIRAC,
            AV_CODEC_ID_BFI => CodecId::BFI,
            AV_CODEC_ID_CMV => CodecId::CMV,
            AV_CODEC_ID_MOTIONPIXELS => CodecId::MOTIONPIXELS,
            AV_CODEC_ID_TGV => CodecId::TGV,
            AV_CODEC_ID_TGQ => CodecId::TGQ,
            AV_CODEC_ID_TQI => CodecId::TQI,
            AV_CODEC_ID_AURA => CodecId::AURA,
            AV_CODEC_ID_AURA2 => CodecId::AURA2,
            AV_CODEC_ID_V210X => CodecId::V210X,
            AV_CODEC_ID_TMV => CodecId::TMV,
            AV_CODEC_ID_V210 => CodecId::V210,
            AV_CODEC_ID_DPX => CodecId::DPX,
            AV_CODEC_ID_MAD => CodecId::MAD,
            AV_CODEC_ID_FRWU => CodecId::FRWU,
            AV_CODEC_ID_FLASHSV2 => CodecId::FLASHSV2,
            AV_CODEC_ID_CDGRAPHICS => CodecId::CDGRAPHICS,
            AV_CODEC_ID_R210 => CodecId::R210,
            AV_CODEC_ID_ANM => CodecId::ANM,
            AV_CODEC_ID_BINKVIDEO => CodecId::BINKVIDEO,
            AV_CODEC_ID_IFF_ILBM => CodecId::IFF_ILBM,
            AV_CODEC_ID_KGV1 => CodecId::KGV1,
            AV_CODEC_ID_YOP => CodecId::YOP,
            AV_CODEC_ID_VP8 => CodecId::VP8,
            AV_CODEC_ID_PICTOR => CodecId::PICTOR,
            AV_CODEC_ID_ANSI => CodecId::ANSI,
            AV_CODEC_ID_A64_MULTI => CodecId::A64_MULTI,
            AV_CODEC_ID_A64_MULTI5 => CodecId::A64_MULTI5,
            AV_CODEC_ID_R10K => CodecId::R10K,
            AV_CODEC_ID_MXPEG => CodecId::MXPEG,
            AV_CODEC_ID_LAGARITH => CodecId::LAGARITH,
            AV_CODEC_ID_PRORES => CodecId::PRORES,
            AV_CODEC_ID_JV => CodecId::JV,
            AV_CODEC_ID_DFA => CodecId::DFA,
            AV_CODEC_ID_WMV3IMAGE => CodecId::WMV3IMAGE,
            AV_CODEC_ID_VC1IMAGE => CodecId::VC1IMAGE,
            AV_CODEC_ID_UTVIDEO => CodecId::UTVIDEO,
            AV_CODEC_ID_BMV_VIDEO => CodecId::BMV_VIDEO,
            AV_CODEC_ID_VBLE => CodecId::VBLE,
            AV_CODEC_ID_DXTORY => CodecId::DXTORY,
            AV_CODEC_ID_V410 => CodecId::V410,
            AV_CODEC_ID_XWD => CodecId::XWD,
            AV_CODEC_ID_CDXL => CodecId::CDXL,
            AV_CODEC_ID_XBM => CodecId::XBM,
            AV_CODEC_ID_ZEROCODEC => CodecId::ZEROCODEC,
            AV_CODEC_ID_MSS1 => CodecId::MSS1,
            AV_CODEC_ID_MSA1 => CodecId::MSA1,
            AV_CODEC_ID_TSCC2 => CodecId::TSCC2,
            AV_CODEC_ID_MTS2 => CodecId::MTS2,
            AV_CODEC_ID_CLLC => CodecId::CLLC,
            AV_CODEC_ID_MSS2 => CodecId::MSS2,
            AV_CODEC_ID_VP9 => CodecId::VP9,
            AV_CODEC_ID_AIC => CodecId::AIC,
            AV_CODEC_ID_ESCAPE130 => CodecId::ESCAPE130,
            AV_CODEC_ID_G2M => CodecId::G2M,
            AV_CODEC_ID_WEBP => CodecId::WEBP,
            AV_CODEC_ID_HNM4_VIDEO => CodecId::HNM4_VIDEO,
            AV_CODEC_ID_HEVC => CodecId::HEVC,
            AV_CODEC_ID_FIC => CodecId::FIC,
            AV_CODEC_ID_ALIAS_PIX => CodecId::ALIAS_PIX,
            AV_CODEC_ID_BRENDER_PIX => CodecId::BRENDER_PIX,
            AV_CODEC_ID_PAF_VIDEO => CodecId::PAF_VIDEO,
            AV_CODEC_ID_EXR => CodecId::EXR,
            AV_CODEC_ID_VP7 => CodecId::VP7,
            AV_CODEC_ID_SANM => CodecId::SANM,
            AV_CODEC_ID_SGIRLE => CodecId::SGIRLE,
            AV_CODEC_ID_MVC1 => CodecId::MVC1,
            AV_CODEC_ID_MVC2 => CodecId::MVC2,
            AV_CODEC_ID_HQX => CodecId::HQX,
            AV_CODEC_ID_TDSC => CodecId::TDSC,
            AV_CODEC_ID_HQ_HQA => CodecId::HQ_HQA,
            AV_CODEC_ID_HAP => CodecId::HAP,
            AV_CODEC_ID_DDS => CodecId::DDS,
            AV_CODEC_ID_DXV => CodecId::DXV,
            AV_CODEC_ID_SCREENPRESSO => CodecId::SCREENPRESSO,
            AV_CODEC_ID_RSCC => CodecId::RSCC,

            AV_CODEC_ID_Y41P => CodecId::Y41P,
            AV_CODEC_ID_AVRP => CodecId::AVRP,
            AV_CODEC_ID_012V => CodecId::V012,
            AV_CODEC_ID_AVUI => CodecId::AVUI,
            AV_CODEC_ID_TARGA_Y216 => CodecId::TARGA_Y216,
            AV_CODEC_ID_V308 => CodecId::V308,
            AV_CODEC_ID_V408 => CodecId::V408,
            AV_CODEC_ID_YUV4 => CodecId::YUV4,
            AV_CODEC_ID_AVRN => CodecId::AVRN,
            AV_CODEC_ID_CPIA => CodecId::CPIA,
            AV_CODEC_ID_XFACE => CodecId::XFACE,
            AV_CODEC_ID_SNOW => CodecId::SNOW,
            AV_CODEC_ID_SMVJPEG => CodecId::SMVJPEG,
            AV_CODEC_ID_APNG => CodecId::APNG,
            AV_CODEC_ID_DAALA => CodecId::DAALA,
            AV_CODEC_ID_CFHD => CodecId::CFHD,
            AV_CODEC_ID_TRUEMOTION2RT => CodecId::TRUEMOTION2RT,
            AV_CODEC_ID_M101 => CodecId::M101,
            AV_CODEC_ID_MAGICYUV => CodecId::MAGICYUV,
            AV_CODEC_ID_SHEERVIDEO => CodecId::SHEERVIDEO,
            AV_CODEC_ID_YLC => CodecId::YLC,

            // PCM codecs
            AV_CODEC_ID_PCM_S16LE => CodecId::PCM_S16LE,
            AV_CODEC_ID_PCM_S16BE => CodecId::PCM_S16BE,
            AV_CODEC_ID_PCM_U16LE => CodecId::PCM_U16LE,
            AV_CODEC_ID_PCM_U16BE => CodecId::PCM_U16BE,
            AV_CODEC_ID_PCM_S8 => CodecId::PCM_S8,
            AV_CODEC_ID_PCM_U8 => CodecId::PCM_U8,
            AV_CODEC_ID_PCM_MULAW => CodecId::PCM_MULAW,
            AV_CODEC_ID_PCM_ALAW => CodecId::PCM_ALAW,
            AV_CODEC_ID_PCM_S32LE => CodecId::PCM_S32LE,
            AV_CODEC_ID_PCM_S32BE => CodecId::PCM_S32BE,
            AV_CODEC_ID_PCM_U32LE => CodecId::PCM_U32LE,
            AV_CODEC_ID_PCM_U32BE => CodecId::PCM_U32BE,
            AV_CODEC_ID_PCM_S24LE => CodecId::PCM_S24LE,
            AV_CODEC_ID_PCM_S24BE => CodecId::PCM_S24BE,
            AV_CODEC_ID_PCM_U24LE => CodecId::PCM_U24LE,
            AV_CODEC_ID_PCM_U24BE => CodecId::PCM_U24BE,
            AV_CODEC_ID_PCM_S24DAUD => CodecId::PCM_S24DAUD,
            AV_CODEC_ID_PCM_ZORK => CodecId::PCM_ZORK,
            AV_CODEC_ID_PCM_S16LE_PLANAR => CodecId::PCM_S16LE_PLANAR,
            AV_CODEC_ID_PCM_DVD => CodecId::PCM_DVD,
            AV_CODEC_ID_PCM_F32BE => CodecId::PCM_F32BE,
            AV_CODEC_ID_PCM_F32LE => CodecId::PCM_F32LE,
            AV_CODEC_ID_PCM_F64BE => CodecId::PCM_F64BE,
            AV_CODEC_ID_PCM_F64LE => CodecId::PCM_F64LE,
            AV_CODEC_ID_PCM_BLURAY => CodecId::PCM_BLURAY,
            AV_CODEC_ID_PCM_LXF => CodecId::PCM_LXF,
            AV_CODEC_ID_S302M => CodecId::S302M,
            AV_CODEC_ID_PCM_S8_PLANAR => CodecId::PCM_S8_PLANAR,
            AV_CODEC_ID_PCM_S24LE_PLANAR => CodecId::PCM_S24LE_PLANAR,
            AV_CODEC_ID_PCM_S32LE_PLANAR => CodecId::PCM_S32LE_PLANAR,
            AV_CODEC_ID_PCM_S16BE_PLANAR => CodecId::PCM_S16BE_PLANAR,
            AV_CODEC_ID_PCM_S64LE => CodecId::PCM_S64LE,
            AV_CODEC_ID_PCM_S64BE => CodecId::PCM_S64BE,

            // ADPCM codecs
            AV_CODEC_ID_ADPCM_IMA_QT => CodecId::ADPCM_IMA_QT,
            AV_CODEC_ID_ADPCM_IMA_WAV => CodecId::ADPCM_IMA_WAV,
            AV_CODEC_ID_ADPCM_IMA_DK3 => CodecId::ADPCM_IMA_DK3,
            AV_CODEC_ID_ADPCM_IMA_DK4 => CodecId::ADPCM_IMA_DK4,
            AV_CODEC_ID_ADPCM_IMA_WS => CodecId::ADPCM_IMA_WS,
            AV_CODEC_ID_ADPCM_IMA_SMJPEG => CodecId::ADPCM_IMA_SMJPEG,
            AV_CODEC_ID_ADPCM_MS => CodecId::ADPCM_MS,
            AV_CODEC_ID_ADPCM_4XM => CodecId::ADPCM_4XM,
            AV_CODEC_ID_ADPCM_XA => CodecId::ADPCM_XA,
            AV_CODEC_ID_ADPCM_ADX => CodecId::ADPCM_ADX,
            AV_CODEC_ID_ADPCM_EA => CodecId::ADPCM_EA,
            AV_CODEC_ID_ADPCM_G726 => CodecId::ADPCM_G726,
            AV_CODEC_ID_ADPCM_CT => CodecId::ADPCM_CT,
            AV_CODEC_ID_ADPCM_SWF => CodecId::ADPCM_SWF,
            AV_CODEC_ID_ADPCM_YAMAHA => CodecId::ADPCM_YAMAHA,
            AV_CODEC_ID_ADPCM_SBPRO_4 => CodecId::ADPCM_SBPRO_4,
            AV_CODEC_ID_ADPCM_SBPRO_3 => CodecId::ADPCM_SBPRO_3,
            AV_CODEC_ID_ADPCM_SBPRO_2 => CodecId::ADPCM_SBPRO_2,
            AV_CODEC_ID_ADPCM_THP => CodecId::ADPCM_THP,
            AV_CODEC_ID_ADPCM_IMA_AMV => CodecId::ADPCM_IMA_AMV,
            AV_CODEC_ID_ADPCM_EA_R1 => CodecId::ADPCM_EA_R1,
            AV_CODEC_ID_ADPCM_EA_R3 => CodecId::ADPCM_EA_R3,
            AV_CODEC_ID_ADPCM_EA_R2 => CodecId::ADPCM_EA_R2,
            AV_CODEC_ID_ADPCM_IMA_EA_SEAD => CodecId::ADPCM_IMA_EA_SEAD,
            AV_CODEC_ID_ADPCM_IMA_EA_EACS => CodecId::ADPCM_IMA_EA_EACS,
            AV_CODEC_ID_ADPCM_EA_XAS => CodecId::ADPCM_EA_XAS,
            AV_CODEC_ID_ADPCM_EA_MAXIS_XA => CodecId::ADPCM_EA_MAXIS_XA,
            AV_CODEC_ID_ADPCM_IMA_ISS => CodecId::ADPCM_IMA_ISS,
            AV_CODEC_ID_ADPCM_G722 => CodecId::ADPCM_G722,
            AV_CODEC_ID_ADPCM_IMA_APC => CodecId::ADPCM_IMA_APC,
            AV_CODEC_ID_ADPCM_VIMA => CodecId::ADPCM_VIMA,
            AV_CODEC_ID_ADPCM_AFC => CodecId::ADPCM_AFC,
            AV_CODEC_ID_ADPCM_IMA_OKI => CodecId::ADPCM_IMA_OKI,
            AV_CODEC_ID_ADPCM_DTK => CodecId::ADPCM_DTK,
            AV_CODEC_ID_ADPCM_IMA_RAD => CodecId::ADPCM_IMA_RAD,
            AV_CODEC_ID_ADPCM_G726LE => CodecId::ADPCM_G726LE,
            AV_CODEC_ID_ADPCM_THP_LE => CodecId::ADPCM_THP_LE,
            AV_CODEC_ID_ADPCM_PSX => CodecId::ADPCM_PSX,
            AV_CODEC_ID_ADPCM_AICA => CodecId::ADPCM_AICA,
            AV_CODEC_ID_ADPCM_IMA_DAT4 => CodecId::ADPCM_IMA_DAT4,
            AV_CODEC_ID_ADPCM_MTAF => CodecId::ADPCM_MTAF,

            // AMR codecs
            AV_CODEC_ID_AMR_NB => CodecId::AMR_NB,
            AV_CODEC_ID_AMR_WB => CodecId::AMR_WB,

            // RealAudio codecs
            AV_CODEC_ID_RA_144 => CodecId::RA_144,
            AV_CODEC_ID_RA_288 => CodecId::RA_288,

            // DPCM codecs
            AV_CODEC_ID_ROQ_DPCM => CodecId::ROQ_DPCM,
            AV_CODEC_ID_INTERPLAY_DPCM => CodecId::INTERPLAY_DPCM,
            AV_CODEC_ID_XAN_DPCM => CodecId::XAN_DPCM,
            AV_CODEC_ID_SOL_DPCM => CodecId::SOL_DPCM,
            AV_CODEC_ID_SDX2_DPCM => CodecId::SDX2_DPCM,

            // Audio codecs
            AV_CODEC_ID_MP2 => CodecId::MP2,
            AV_CODEC_ID_MP3 => CodecId::MP3,
            AV_CODEC_ID_AAC => CodecId::AAC,
            AV_CODEC_ID_AC3 => CodecId::AC3,
            AV_CODEC_ID_DTS => CodecId::DTS,
            AV_CODEC_ID_VORBIS => CodecId::VORBIS,
            AV_CODEC_ID_DVAUDIO => CodecId::DVAUDIO,
            AV_CODEC_ID_WMAV1 => CodecId::WMAV1,
            AV_CODEC_ID_WMAV2 => CodecId::WMAV2,
            AV_CODEC_ID_MACE3 => CodecId::MACE3,
            AV_CODEC_ID_MACE6 => CodecId::MACE6,
            AV_CODEC_ID_VMDAUDIO => CodecId::VMDAUDIO,
            AV_CODEC_ID_FLAC => CodecId::FLAC,
            AV_CODEC_ID_MP3ADU => CodecId::MP3ADU,
            AV_CODEC_ID_MP3ON4 => CodecId::MP3ON4,
            AV_CODEC_ID_SHORTEN => CodecId::SHORTEN,
            AV_CODEC_ID_ALAC => CodecId::ALAC,
            AV_CODEC_ID_WESTWOOD_SND1 => CodecId::WESTWOOD_SND1,
            AV_CODEC_ID_GSM => CodecId::GSM,
            AV_CODEC_ID_QDM2 => CodecId::QDM2,
            AV_CODEC_ID_COOK => CodecId::COOK,
            AV_CODEC_ID_TRUESPEECH => CodecId::TRUESPEECH,
            AV_CODEC_ID_TTA => CodecId::TTA,
            AV_CODEC_ID_SMACKAUDIO => CodecId::SMACKAUDIO,
            AV_CODEC_ID_QCELP => CodecId::QCELP,
            AV_CODEC_ID_WAVPACK => CodecId::WAVPACK,
            AV_CODEC_ID_DSICINAUDIO => CodecId::DSICINAUDIO,
            AV_CODEC_ID_IMC => CodecId::IMC,
            AV_CODEC_ID_MUSEPACK7 => CodecId::MUSEPACK7,
            AV_CODEC_ID_MLP => CodecId::MLP,
            AV_CODEC_ID_GSM_MS => CodecId::GSM_MS,
            AV_CODEC_ID_ATRAC3 => CodecId::ATRAC3,
            AV_CODEC_ID_APE => CodecId::APE,
            AV_CODEC_ID_NELLYMOSER => CodecId::NELLYMOSER,
            AV_CODEC_ID_MUSEPACK8 => CodecId::MUSEPACK8,
            AV_CODEC_ID_SPEEX => CodecId::SPEEX,
            AV_CODEC_ID_WMAVOICE => CodecId::WMAVOICE,
            AV_CODEC_ID_WMAPRO => CodecId::WMAPRO,
            AV_CODEC_ID_WMALOSSLESS => CodecId::WMALOSSLESS,
            AV_CODEC_ID_ATRAC3P => CodecId::ATRAC3P,
            AV_CODEC_ID_EAC3 => CodecId::EAC3,
            AV_CODEC_ID_SIPR => CodecId::SIPR,
            AV_CODEC_ID_MP1 => CodecId::MP1,
            AV_CODEC_ID_TWINVQ => CodecId::TWINVQ,
            AV_CODEC_ID_TRUEHD => CodecId::TRUEHD,
            AV_CODEC_ID_MP4ALS => CodecId::MP4ALS,
            AV_CODEC_ID_ATRAC1 => CodecId::ATRAC1,
            AV_CODEC_ID_BINKAUDIO_RDFT => CodecId::BINKAUDIO_RDFT,
            AV_CODEC_ID_BINKAUDIO_DCT => CodecId::BINKAUDIO_DCT,
            AV_CODEC_ID_AAC_LATM => CodecId::AAC_LATM,
            AV_CODEC_ID_QDMC => CodecId::QDMC,
            AV_CODEC_ID_CELT => CodecId::CELT,
            AV_CODEC_ID_G723_1 => CodecId::G723_1,
            AV_CODEC_ID_G729 => CodecId::G729,
            AV_CODEC_ID_8SVX_EXP => CodecId::SVX_EXP8,
            AV_CODEC_ID_8SVX_FIB => CodecId::SVX_FIB8,
            AV_CODEC_ID_BMV_AUDIO => CodecId::BMV_AUDIO,
            AV_CODEC_ID_RALF => CodecId::RALF,
            AV_CODEC_ID_IAC => CodecId::IAC,
            AV_CODEC_ID_ILBC => CodecId::ILBC,
            AV_CODEC_ID_OPUS => CodecId::OPUS,
            AV_CODEC_ID_COMFORT_NOISE => CodecId::COMFORT_NOISE,
            AV_CODEC_ID_TAK => CodecId::TAK,
            AV_CODEC_ID_METASOUND => CodecId::METASOUND,
            AV_CODEC_ID_PAF_AUDIO => CodecId::PAF_AUDIO,
            AV_CODEC_ID_ON2AVC => CodecId::ON2AVC,
            AV_CODEC_ID_DSS_SP => CodecId::DSS_SP,
            AV_CODEC_ID_CODEC2 => CodecId::CODEC2,
            AV_CODEC_ID_FFWAVESYNTH => CodecId::FFWAVESYNTH,
            AV_CODEC_ID_SONIC => CodecId::SONIC,
            AV_CODEC_ID_SONIC_LS => CodecId::SONIC_LS,
            AV_CODEC_ID_EVRC => CodecId::EVRC,
            AV_CODEC_ID_SMV => CodecId::SMV,
            AV_CODEC_ID_DSD_LSBF => CodecId::DSD_LSBF,
            AV_CODEC_ID_DSD_MSBF => CodecId::DSD_MSBF,
            AV_CODEC_ID_DSD_LSBF_PLANAR => CodecId::DSD_LSBF_PLANAR,
            AV_CODEC_ID_DSD_MSBF_PLANAR => CodecId::DSD_MSBF_PLANAR,
            AV_CODEC_ID_4GV => CodecId::_4GV,
            AV_CODEC_ID_INTERPLAY_ACM => CodecId::INTERPLAY_ACM,
            AV_CODEC_ID_XMA1 => CodecId::XMA1,
            AV_CODEC_ID_XMA2 => CodecId::XMA2,
            AV_CODEC_ID_DST => CodecId::DST,

            // Subtitle codecs
            AV_CODEC_ID_DVD_SUBTITLE => CodecId::DVD_SUBTITLE,
            AV_CODEC_ID_DVB_SUBTITLE => CodecId::DVB_SUBTITLE,
            AV_CODEC_ID_TEXT => CodecId::TEXT,
            AV_CODEC_ID_XSUB => CodecId::XSUB,
            AV_CODEC_ID_SSA => CodecId::SSA,
            AV_CODEC_ID_MOV_TEXT => CodecId::MOV_TEXT,
            AV_CODEC_ID_HDMV_PGS_SUBTITLE => CodecId::HDMV_PGS_SUBTITLE,
            AV_CODEC_ID_DVB_TELETEXT => CodecId::DVB_TELETEXT,
            AV_CODEC_ID_SRT => CodecId::SRT,
            AV_CODEC_ID_MICRODVD => CodecId::MICRODVD,
            AV_CODEC_ID_EIA_608 => CodecId::EIA_608,
            AV_CODEC_ID_JACOSUB => CodecId::JACOSUB,
            AV_CODEC_ID_SAMI => CodecId::SAMI,
            AV_CODEC_ID_REALTEXT => CodecId::REALTEXT,
            AV_CODEC_ID_STL => CodecId::STL,
            AV_CODEC_ID_SUBVIEWER1 => CodecId::SUBVIEWER1,
            AV_CODEC_ID_SUBVIEWER => CodecId::SUBVIEWER,
            AV_CODEC_ID_SUBRIP => CodecId::SUBRIP,
            AV_CODEC_ID_WEBVTT => CodecId::WEBVTT,
            AV_CODEC_ID_MPL2 => CodecId::MPL2,
            AV_CODEC_ID_VPLAYER => CodecId::VPLAYER,
            AV_CODEC_ID_PJS => CodecId::PJS,
            AV_CODEC_ID_ASS => CodecId::ASS,
            AV_CODEC_ID_HDMV_TEXT_SUBTITLE => CodecId::HDMV_TEXT_SUBTITLE,

            // Other codecs
            AV_CODEC_ID_TTF => CodecId::TTF,
            AV_CODEC_ID_SCTE_35 => CodecId::SCTE_35,
            AV_CODEC_ID_BINTEXT => CodecId::BINTEXT,
            AV_CODEC_ID_XBIN => CodecId::XBIN,
            AV_CODEC_ID_IDF => CodecId::IDF,
            AV_CODEC_ID_OTF => CodecId::OTF,
            AV_CODEC_ID_SMPTE_KLV => CodecId::SMPTE_KLV,
            AV_CODEC_ID_DVD_NAV => CodecId::DVD_NAV,
            AV_CODEC_ID_TIMED_ID3 => CodecId::TIMED_ID3,
            AV_CODEC_ID_BIN_DATA => CodecId::BIN_DATA,
            AV_CODEC_ID_PROBE => CodecId::PROBE,
            AV_CODEC_ID_MPEG2TS => CodecId::MPEG2TS,
            AV_CODEC_ID_MPEG4SYSTEMS => CodecId::MPEG4SYSTEMS,
            AV_CODEC_ID_FFMETADATA => CodecId::FFMETADATA,
            AV_CODEC_ID_WRAPPED_AVFRAME => CodecId::WRAPPED_AVFRAME,
            AV_CODEC_ID_PSD => CodecId::PSD,
            AV_CODEC_ID_PIXLET => CodecId::PIXLET,
            AV_CODEC_ID_SPEEDHQ => CodecId::SPEEDHQ,
            AV_CODEC_ID_CLEARVIDEO => CodecId::CLEARVIDEO,
            AV_CODEC_ID_FMVC => CodecId::FMVC,
            AV_CODEC_ID_SCPR => CodecId::SCPR,
            AV_CODEC_ID_XPM => CodecId::XPM,
            AV_CODEC_ID_AV1 => CodecId::AV1,
            AV_CODEC_ID_PCM_F16LE => CodecId::PCM_F16LE,
            AV_CODEC_ID_PCM_F24LE => CodecId::PCM_F24LE,
            AV_CODEC_ID_ATRAC3AL => CodecId::ATRAC3AL,
            AV_CODEC_ID_ATRAC3PAL => CodecId::ATRAC3PAL,
            AV_CODEC_ID_BITPACKED => CodecId::BITPACKED,
            AV_CODEC_ID_MSCC => CodecId::MSCC,
            AV_CODEC_ID_SRGC => CodecId::SRGC,
            AV_CODEC_ID_SVG => CodecId::SVG,
            AV_CODEC_ID_GDV => CodecId::GDV,
            AV_CODEC_ID_FITS => CodecId::FITS,
            AV_CODEC_ID_GREMLIN_DPCM => CodecId::GREMLIN_DPCM,
            AV_CODEC_ID_DOLBY_E => CodecId::DOLBY_E,
            AV_CODEC_ID_APTX => CodecId::APTX,
            AV_CODEC_ID_APTX_HD => CodecId::APTX_HD,
            AV_CODEC_ID_SBC => CodecId::SBC,
            AV_CODEC_ID_AVS2 => CodecId::AVS2,
            AV_CODEC_ID_IMM4 => CodecId::IMM4,
            AV_CODEC_ID_PROSUMER => CodecId::PROSUMER,
            AV_CODEC_ID_MWSC => CodecId::MWSC,
            AV_CODEC_ID_WCMV => CodecId::WCMV,
            AV_CODEC_ID_RASC => CodecId::RASC,
            AV_CODEC_ID_PCM_VIDC => CodecId::PCM_VIDC,
            AV_CODEC_ID_ATRAC9 => CodecId::ATRAC9,
            AV_CODEC_ID_TTML => CodecId::TTML,
            AV_CODEC_ID_HYMT => CodecId::HYMT,
            AV_CODEC_ID_ARBC => CodecId::ARBC,
            AV_CODEC_ID_AGM => CodecId::AGM,
            AV_CODEC_ID_LSCR => CodecId::LSCR,
            AV_CODEC_ID_VP4 => CodecId::VP4,
            AV_CODEC_ID_ADPCM_AGM => CodecId::ADPCM_AGM,
            AV_CODEC_ID_HCOM => CodecId::HCOM,
            AV_CODEC_ID_ARIB_CAPTION => CodecId::ARIB_CAPTION,
            AV_CODEC_ID_IMM5 => CodecId::IMM5,
            AV_CODEC_ID_MVDV => CodecId::MVDV,
            AV_CODEC_ID_MVHA => CodecId::MVHA,
            AV_CODEC_ID_CDTOONS => CodecId::CDTOONS,
            AV_CODEC_ID_MV30 => CodecId::MV30,
            AV_CODEC_ID_NOTCHLC => CodecId::NOTCHLC,
            AV_CODEC_ID_PFM => CodecId::PFM,
            AV_CODEC_ID_ADPCM_ARGO => CodecId::ADPCM_ARGO,
            AV_CODEC_ID_ADPCM_IMA_SSI => CodecId::ADPCM_IMA_SSI,
            AV_CODEC_ID_ADPCM_ZORK => CodecId::ADPCM_ZORK,
            AV_CODEC_ID_ADPCM_IMA_APM => CodecId::ADPCM_IMA_APM,
            AV_CODEC_ID_ADPCM_IMA_ALP => CodecId::ADPCM_IMA_ALP,
            AV_CODEC_ID_ADPCM_IMA_MTF => CodecId::ADPCM_IMA_MTF,
            AV_CODEC_ID_ADPCM_IMA_CUNNING => CodecId::ADPCM_IMA_CUNNING,
            AV_CODEC_ID_DERF_DPCM => CodecId::DERF_DPCM,
            AV_CODEC_ID_ACELP_KELVIN => CodecId::ACELP_KELVIN,
            AV_CODEC_ID_MPEGH_3D_AUDIO => CodecId::MPEGH_3D_AUDIO,
            AV_CODEC_ID_SIREN => CodecId::SIREN,
            AV_CODEC_ID_HCA => CodecId::HCA,
            AV_CODEC_ID_EPG => CodecId::EPG,
            AV_CODEC_ID_PGX => CodecId::PGX,
            AV_CODEC_ID_AVS3 => CodecId::AVS3,
            AV_CODEC_ID_MSP2 => CodecId::MSP2,
            AV_CODEC_ID_VVC => CodecId::VVC,
            AV_CODEC_ID_MOBICLIP => CodecId::MOBICLIP,
            AV_CODEC_ID_PHOTOCD => CodecId::PHOTOCD,
            AV_CODEC_ID_IPU => CodecId::IPU,
            AV_CODEC_ID_ARGO => CodecId::ARGO,
            AV_CODEC_ID_CRI => CodecId::CRI,
            AV_CODEC_ID_SIMBIOSIS_IMX => CodecId::SIMBIOSIS_IMX,
            AV_CODEC_ID_SGA_VIDEO => CodecId::SGA_VIDEO,
            AV_CODEC_ID_PCM_SGA => CodecId::PCM_SGA,
            AV_CODEC_ID_ADPCM_IMA_MOFLEX => CodecId::ADPCM_IMA_MOFLEX,
            AV_CODEC_ID_FASTAUDIO => CodecId::FASTAUDIO,
            AV_CODEC_ID_GEM => CodecId::GEM,
            AV_CODEC_ID_ADPCM_IMA_ACORN => CodecId::ADPCM_IMA_ACORN,
            AV_CODEC_ID_MSNSIREN => CodecId::MSNSIREN,
            AV_CODEC_ID_VBN => CodecId::VBN,
            AV_CODEC_ID_JPEGXL => CodecId::JPEGXL,
            AV_CODEC_ID_QOI => CodecId::QOI,
            AV_CODEC_ID_PHM => CodecId::PHM,
            AV_CODEC_ID_DFPWM => CodecId::DFPWM,
            AV_CODEC_ID_RADIANCE_HDR => CodecId::RADIANCE_HDR,
            AV_CODEC_ID_WBMP => CodecId::WBMP,
            AV_CODEC_ID_MEDIA100 => CodecId::MEDIA100,
            AV_CODEC_ID_VQC => CodecId::VQC,
            AV_CODEC_ID_ADPCM_XMD => CodecId::ADPCM_XMD,
            AV_CODEC_ID_WADY_DPCM => CodecId::WADY_DPCM,
            AV_CODEC_ID_CBD2_DPCM => CodecId::CBD2_DPCM,
            AV_CODEC_ID_BONK => CodecId::BONK,
            AV_CODEC_ID_MISC4 => CodecId::MISC4,
            AV_CODEC_ID_APAC => CodecId::APAC,
            AV_CODEC_ID_FTR => CodecId::FTR,
            AV_CODEC_ID_WAVARC => CodecId::WAVARC,
            AV_CODEC_ID_RKA => CodecId::RKA,
            AV_CODEC_ID_VNULL => CodecId::VNULL,
            AV_CODEC_ID_ANULL => CodecId::ANULL,
            AV_CODEC_ID_PDV => CodecId::PDV,
            AV_CODEC_ID_EVC => CodecId::EVC,
            AV_CODEC_ID_RTV1 => CodecId::RTV1,
            AV_CODEC_ID_VMIX => CodecId::VMIX,
            AV_CODEC_ID_AC4 => CodecId::AC4,
            AV_CODEC_ID_SMPTE_2038 => CodecId::SMPTE_2038,
            AV_CODEC_ID_OSQ => CodecId::OSQ,

            AV_CODEC_ID_LEAD => CodecId::LEAD,
            AV_CODEC_ID_QOA => CodecId::QOA,
        }
    }
}

impl From<CodecId> for ffi::AVCodecID {
    fn from(value: CodecId) -> ffi::AVCodecID {
        use ffi::AVCodecID::*;

        match value {
            CodecId::None => AV_CODEC_ID_NONE,

            // Video codecs
            CodecId::MPEG1VIDEO => AV_CODEC_ID_MPEG1VIDEO,
            CodecId::MPEG2VIDEO => AV_CODEC_ID_MPEG2VIDEO,
            CodecId::H261 => AV_CODEC_ID_H261,
            CodecId::H263 => AV_CODEC_ID_H263,
            CodecId::RV10 => AV_CODEC_ID_RV10,
            CodecId::RV20 => AV_CODEC_ID_RV20,
            CodecId::MJPEG => AV_CODEC_ID_MJPEG,
            CodecId::MJPEGB => AV_CODEC_ID_MJPEGB,
            CodecId::LJPEG => AV_CODEC_ID_LJPEG,
            CodecId::SP5X => AV_CODEC_ID_SP5X,
            CodecId::JPEGLS => AV_CODEC_ID_JPEGLS,
            CodecId::MPEG4 => AV_CODEC_ID_MPEG4,
            CodecId::RAWVIDEO => AV_CODEC_ID_RAWVIDEO,
            CodecId::MSMPEG4V1 => AV_CODEC_ID_MSMPEG4V1,
            CodecId::MSMPEG4V2 => AV_CODEC_ID_MSMPEG4V2,
            CodecId::MSMPEG4V3 => AV_CODEC_ID_MSMPEG4V3,
            CodecId::WMV1 => AV_CODEC_ID_WMV1,
            CodecId::WMV2 => AV_CODEC_ID_WMV2,
            CodecId::H263P => AV_CODEC_ID_H263P,
            CodecId::H263I => AV_CODEC_ID_H263I,
            CodecId::FLV1 => AV_CODEC_ID_FLV1,
            CodecId::SVQ1 => AV_CODEC_ID_SVQ1,
            CodecId::SVQ3 => AV_CODEC_ID_SVQ3,
            CodecId::DVVIDEO => AV_CODEC_ID_DVVIDEO,
            CodecId::HUFFYUV => AV_CODEC_ID_HUFFYUV,
            CodecId::CYUV => AV_CODEC_ID_CYUV,
            CodecId::H264 => AV_CODEC_ID_H264,
            CodecId::INDEO3 => AV_CODEC_ID_INDEO3,
            CodecId::VP3 => AV_CODEC_ID_VP3,
            CodecId::THEORA => AV_CODEC_ID_THEORA,
            CodecId::ASV1 => AV_CODEC_ID_ASV1,
            CodecId::ASV2 => AV_CODEC_ID_ASV2,
            CodecId::FFV1 => AV_CODEC_ID_FFV1,
            CodecId::XM4 => AV_CODEC_ID_4XM,
            CodecId::VCR1 => AV_CODEC_ID_VCR1,
            CodecId::CLJR => AV_CODEC_ID_CLJR,
            CodecId::MDEC => AV_CODEC_ID_MDEC,
            CodecId::ROQ => AV_CODEC_ID_ROQ,
            CodecId::INTERPLAY_VIDEO => AV_CODEC_ID_INTERPLAY_VIDEO,
            CodecId::XAN_WC3 => AV_CODEC_ID_XAN_WC3,
            CodecId::XAN_WC4 => AV_CODEC_ID_XAN_WC4,
            CodecId::RPZA => AV_CODEC_ID_RPZA,
            CodecId::CINEPAK => AV_CODEC_ID_CINEPAK,
            CodecId::WS_VQA => AV_CODEC_ID_WS_VQA,
            CodecId::MSRLE => AV_CODEC_ID_MSRLE,
            CodecId::MSVIDEO1 => AV_CODEC_ID_MSVIDEO1,
            CodecId::IDCIN => AV_CODEC_ID_IDCIN,
            CodecId::BPS8 => AV_CODEC_ID_8BPS,
            CodecId::SMC => AV_CODEC_ID_SMC,
            CodecId::FLIC => AV_CODEC_ID_FLIC,
            CodecId::TRUEMOTION1 => AV_CODEC_ID_TRUEMOTION1,
            CodecId::VMDVIDEO => AV_CODEC_ID_VMDVIDEO,
            CodecId::MSZH => AV_CODEC_ID_MSZH,
            CodecId::ZLIB => AV_CODEC_ID_ZLIB,
            CodecId::QTRLE => AV_CODEC_ID_QTRLE,
            CodecId::TSCC => AV_CODEC_ID_TSCC,
            CodecId::ULTI => AV_CODEC_ID_ULTI,
            CodecId::QDRAW => AV_CODEC_ID_QDRAW,
            CodecId::VIXL => AV_CODEC_ID_VIXL,
            CodecId::QPEG => AV_CODEC_ID_QPEG,
            CodecId::PNG => AV_CODEC_ID_PNG,
            CodecId::PPM => AV_CODEC_ID_PPM,
            CodecId::PBM => AV_CODEC_ID_PBM,
            CodecId::PGM => AV_CODEC_ID_PGM,
            CodecId::PGMYUV => AV_CODEC_ID_PGMYUV,
            CodecId::PAM => AV_CODEC_ID_PAM,
            CodecId::FFVHUFF => AV_CODEC_ID_FFVHUFF,
            CodecId::RV30 => AV_CODEC_ID_RV30,
            CodecId::RV40 => AV_CODEC_ID_RV40,
            CodecId::VC1 => AV_CODEC_ID_VC1,
            CodecId::WMV3 => AV_CODEC_ID_WMV3,
            CodecId::LOCO => AV_CODEC_ID_LOCO,
            CodecId::WNV1 => AV_CODEC_ID_WNV1,
            CodecId::AASC => AV_CODEC_ID_AASC,
            CodecId::INDEO2 => AV_CODEC_ID_INDEO2,
            CodecId::FRAPS => AV_CODEC_ID_FRAPS,
            CodecId::TRUEMOTION2 => AV_CODEC_ID_TRUEMOTION2,
            CodecId::BMP => AV_CODEC_ID_BMP,
            CodecId::CSCD => AV_CODEC_ID_CSCD,
            CodecId::MMVIDEO => AV_CODEC_ID_MMVIDEO,
            CodecId::ZMBV => AV_CODEC_ID_ZMBV,
            CodecId::AVS => AV_CODEC_ID_AVS,
            CodecId::SMACKVIDEO => AV_CODEC_ID_SMACKVIDEO,
            CodecId::NUV => AV_CODEC_ID_NUV,
            CodecId::KMVC => AV_CODEC_ID_KMVC,
            CodecId::FLASHSV => AV_CODEC_ID_FLASHSV,
            CodecId::CAVS => AV_CODEC_ID_CAVS,
            CodecId::JPEG2000 => AV_CODEC_ID_JPEG2000,
            CodecId::VMNC => AV_CODEC_ID_VMNC,
            CodecId::VP5 => AV_CODEC_ID_VP5,
            CodecId::VP6 => AV_CODEC_ID_VP6,
            CodecId::VP6F => AV_CODEC_ID_VP6F,
            CodecId::TARGA => AV_CODEC_ID_TARGA,
            CodecId::DSICINVIDEO => AV_CODEC_ID_DSICINVIDEO,
            CodecId::TIERTEXSEQVIDEO => AV_CODEC_ID_TIERTEXSEQVIDEO,
            CodecId::TIFF => AV_CODEC_ID_TIFF,
            CodecId::GIF => AV_CODEC_ID_GIF,
            CodecId::DXA => AV_CODEC_ID_DXA,
            CodecId::DNXHD => AV_CODEC_ID_DNXHD,
            CodecId::THP => AV_CODEC_ID_THP,
            CodecId::SGI => AV_CODEC_ID_SGI,
            CodecId::C93 => AV_CODEC_ID_C93,
            CodecId::BETHSOFTVID => AV_CODEC_ID_BETHSOFTVID,
            CodecId::PTX => AV_CODEC_ID_PTX,
            CodecId::TXD => AV_CODEC_ID_TXD,
            CodecId::VP6A => AV_CODEC_ID_VP6A,
            CodecId::AMV => AV_CODEC_ID_AMV,
            CodecId::VB => AV_CODEC_ID_VB,
            CodecId::PCX => AV_CODEC_ID_PCX,
            CodecId::SUNRAST => AV_CODEC_ID_SUNRAST,
            CodecId::INDEO4 => AV_CODEC_ID_INDEO4,
            CodecId::INDEO5 => AV_CODEC_ID_INDEO5,
            CodecId::MIMIC => AV_CODEC_ID_MIMIC,
            CodecId::RL2 => AV_CODEC_ID_RL2,
            CodecId::ESCAPE124 => AV_CODEC_ID_ESCAPE124,
            CodecId::DIRAC => AV_CODEC_ID_DIRAC,
            CodecId::BFI => AV_CODEC_ID_BFI,
            CodecId::CMV => AV_CODEC_ID_CMV,
            CodecId::MOTIONPIXELS => AV_CODEC_ID_MOTIONPIXELS,
            CodecId::TGV => AV_CODEC_ID_TGV,
            CodecId::TGQ => AV_CODEC_ID_TGQ,
            CodecId::TQI => AV_CODEC_ID_TQI,
            CodecId::AURA => AV_CODEC_ID_AURA,
            CodecId::AURA2 => AV_CODEC_ID_AURA2,
            CodecId::V210X => AV_CODEC_ID_V210X,
            CodecId::TMV => AV_CODEC_ID_TMV,
            CodecId::V210 => AV_CODEC_ID_V210,
            CodecId::DPX => AV_CODEC_ID_DPX,
            CodecId::MAD => AV_CODEC_ID_MAD,
            CodecId::FRWU => AV_CODEC_ID_FRWU,
            CodecId::FLASHSV2 => AV_CODEC_ID_FLASHSV2,
            CodecId::CDGRAPHICS => AV_CODEC_ID_CDGRAPHICS,
            CodecId::R210 => AV_CODEC_ID_R210,
            CodecId::ANM => AV_CODEC_ID_ANM,
            CodecId::BINKVIDEO => AV_CODEC_ID_BINKVIDEO,
            CodecId::IFF_ILBM => AV_CODEC_ID_IFF_ILBM,
            CodecId::IFF_BYTERUN1 => AV_CODEC_ID_IFF_ILBM,
            CodecId::KGV1 => AV_CODEC_ID_KGV1,
            CodecId::YOP => AV_CODEC_ID_YOP,
            CodecId::VP8 => AV_CODEC_ID_VP8,
            CodecId::PICTOR => AV_CODEC_ID_PICTOR,
            CodecId::ANSI => AV_CODEC_ID_ANSI,
            CodecId::A64_MULTI => AV_CODEC_ID_A64_MULTI,
            CodecId::A64_MULTI5 => AV_CODEC_ID_A64_MULTI5,
            CodecId::R10K => AV_CODEC_ID_R10K,
            CodecId::MXPEG => AV_CODEC_ID_MXPEG,
            CodecId::LAGARITH => AV_CODEC_ID_LAGARITH,
            CodecId::PRORES => AV_CODEC_ID_PRORES,
            CodecId::JV => AV_CODEC_ID_JV,
            CodecId::DFA => AV_CODEC_ID_DFA,
            CodecId::WMV3IMAGE => AV_CODEC_ID_WMV3IMAGE,
            CodecId::VC1IMAGE => AV_CODEC_ID_VC1IMAGE,
            CodecId::UTVIDEO => AV_CODEC_ID_UTVIDEO,
            CodecId::BMV_VIDEO => AV_CODEC_ID_BMV_VIDEO,
            CodecId::VBLE => AV_CODEC_ID_VBLE,
            CodecId::DXTORY => AV_CODEC_ID_DXTORY,
            CodecId::V410 => AV_CODEC_ID_V410,
            CodecId::XWD => AV_CODEC_ID_XWD,
            CodecId::CDXL => AV_CODEC_ID_CDXL,
            CodecId::XBM => AV_CODEC_ID_XBM,
            CodecId::ZEROCODEC => AV_CODEC_ID_ZEROCODEC,
            CodecId::MSS1 => AV_CODEC_ID_MSS1,
            CodecId::MSA1 => AV_CODEC_ID_MSA1,
            CodecId::TSCC2 => AV_CODEC_ID_TSCC2,
            CodecId::MTS2 => AV_CODEC_ID_MTS2,
            CodecId::CLLC => AV_CODEC_ID_CLLC,
            CodecId::MSS2 => AV_CODEC_ID_MSS2,
            CodecId::VP9 => AV_CODEC_ID_VP9,
            CodecId::AIC => AV_CODEC_ID_AIC,
            CodecId::ESCAPE130 => AV_CODEC_ID_ESCAPE130,
            CodecId::G2M => AV_CODEC_ID_G2M,
            CodecId::WEBP => AV_CODEC_ID_WEBP,
            CodecId::HNM4_VIDEO => AV_CODEC_ID_HNM4_VIDEO,
            CodecId::HEVC => AV_CODEC_ID_HEVC,
            CodecId::H265 => AV_CODEC_ID_HEVC,
            CodecId::FIC => AV_CODEC_ID_FIC,
            CodecId::ALIAS_PIX => AV_CODEC_ID_ALIAS_PIX,
            CodecId::BRENDER_PIX => AV_CODEC_ID_BRENDER_PIX,
            CodecId::PAF_VIDEO => AV_CODEC_ID_PAF_VIDEO,
            CodecId::EXR => AV_CODEC_ID_EXR,
            CodecId::VP7 => AV_CODEC_ID_VP7,
            CodecId::SANM => AV_CODEC_ID_SANM,
            CodecId::SGIRLE => AV_CODEC_ID_SGIRLE,
            CodecId::MVC1 => AV_CODEC_ID_MVC1,
            CodecId::MVC2 => AV_CODEC_ID_MVC2,
            CodecId::HQX => AV_CODEC_ID_HQX,
            CodecId::TDSC => AV_CODEC_ID_TDSC,
            CodecId::HQ_HQA => AV_CODEC_ID_HQ_HQA,
            CodecId::HAP => AV_CODEC_ID_HAP,
            CodecId::DDS => AV_CODEC_ID_DDS,
            CodecId::DXV => AV_CODEC_ID_DXV,
            CodecId::SCREENPRESSO => AV_CODEC_ID_SCREENPRESSO,
            CodecId::RSCC => AV_CODEC_ID_RSCC,
            CodecId::Y41P => AV_CODEC_ID_Y41P,
            CodecId::AVRP => AV_CODEC_ID_AVRP,
            CodecId::V012 => AV_CODEC_ID_012V,
            CodecId::AVUI => AV_CODEC_ID_AVUI,
            CodecId::TARGA_Y216 => AV_CODEC_ID_TARGA_Y216,
            CodecId::V308 => AV_CODEC_ID_V308,
            CodecId::V408 => AV_CODEC_ID_V408,
            CodecId::YUV4 => AV_CODEC_ID_YUV4,
            CodecId::AVRN => AV_CODEC_ID_AVRN,
            CodecId::CPIA => AV_CODEC_ID_CPIA,
            CodecId::XFACE => AV_CODEC_ID_XFACE,
            CodecId::SNOW => AV_CODEC_ID_SNOW,
            CodecId::SMVJPEG => AV_CODEC_ID_SMVJPEG,
            CodecId::APNG => AV_CODEC_ID_APNG,
            CodecId::DAALA => AV_CODEC_ID_DAALA,
            CodecId::CFHD => AV_CODEC_ID_CFHD,
            CodecId::TRUEMOTION2RT => AV_CODEC_ID_TRUEMOTION2RT,
            CodecId::M101 => AV_CODEC_ID_M101,
            CodecId::MAGICYUV => AV_CODEC_ID_MAGICYUV,
            CodecId::SHEERVIDEO => AV_CODEC_ID_SHEERVIDEO,
            CodecId::YLC => AV_CODEC_ID_YLC,

            // PCM codecs
            CodecId::PCM_S16LE => AV_CODEC_ID_PCM_S16LE,
            CodecId::PCM_S16BE => AV_CODEC_ID_PCM_S16BE,
            CodecId::PCM_U16LE => AV_CODEC_ID_PCM_U16LE,
            CodecId::PCM_U16BE => AV_CODEC_ID_PCM_U16BE,
            CodecId::PCM_S8 => AV_CODEC_ID_PCM_S8,
            CodecId::PCM_U8 => AV_CODEC_ID_PCM_U8,
            CodecId::PCM_MULAW => AV_CODEC_ID_PCM_MULAW,
            CodecId::PCM_ALAW => AV_CODEC_ID_PCM_ALAW,
            CodecId::PCM_S32LE => AV_CODEC_ID_PCM_S32LE,
            CodecId::PCM_S32BE => AV_CODEC_ID_PCM_S32BE,
            CodecId::PCM_U32LE => AV_CODEC_ID_PCM_U32LE,
            CodecId::PCM_U32BE => AV_CODEC_ID_PCM_U32BE,
            CodecId::PCM_S24LE => AV_CODEC_ID_PCM_S24LE,
            CodecId::PCM_S24BE => AV_CODEC_ID_PCM_S24BE,
            CodecId::PCM_U24LE => AV_CODEC_ID_PCM_U24LE,
            CodecId::PCM_U24BE => AV_CODEC_ID_PCM_U24BE,
            CodecId::PCM_S24DAUD => AV_CODEC_ID_PCM_S24DAUD,
            CodecId::PCM_ZORK => AV_CODEC_ID_PCM_ZORK,
            CodecId::PCM_S16LE_PLANAR => AV_CODEC_ID_PCM_S16LE_PLANAR,
            CodecId::PCM_DVD => AV_CODEC_ID_PCM_DVD,
            CodecId::PCM_F32BE => AV_CODEC_ID_PCM_F32BE,
            CodecId::PCM_F32LE => AV_CODEC_ID_PCM_F32LE,
            CodecId::PCM_F64BE => AV_CODEC_ID_PCM_F64BE,
            CodecId::PCM_F64LE => AV_CODEC_ID_PCM_F64LE,
            CodecId::PCM_BLURAY => AV_CODEC_ID_PCM_BLURAY,
            CodecId::PCM_LXF => AV_CODEC_ID_PCM_LXF,
            CodecId::S302M => AV_CODEC_ID_S302M,
            CodecId::PCM_S8_PLANAR => AV_CODEC_ID_PCM_S8_PLANAR,
            CodecId::PCM_S24LE_PLANAR => AV_CODEC_ID_PCM_S24LE_PLANAR,
            CodecId::PCM_S32LE_PLANAR => AV_CODEC_ID_PCM_S32LE_PLANAR,
            CodecId::PCM_S16BE_PLANAR => AV_CODEC_ID_PCM_S16BE_PLANAR,
            CodecId::PCM_S64LE => AV_CODEC_ID_PCM_S64LE,
            CodecId::PCM_S64BE => AV_CODEC_ID_PCM_S64BE,

            // ADPCM codecs
            CodecId::ADPCM_IMA_QT => AV_CODEC_ID_ADPCM_IMA_QT,
            CodecId::ADPCM_IMA_WAV => AV_CODEC_ID_ADPCM_IMA_WAV,
            CodecId::ADPCM_IMA_DK3 => AV_CODEC_ID_ADPCM_IMA_DK3,
            CodecId::ADPCM_IMA_DK4 => AV_CODEC_ID_ADPCM_IMA_DK4,
            CodecId::ADPCM_IMA_WS => AV_CODEC_ID_ADPCM_IMA_WS,
            CodecId::ADPCM_IMA_SMJPEG => AV_CODEC_ID_ADPCM_IMA_SMJPEG,
            CodecId::ADPCM_MS => AV_CODEC_ID_ADPCM_MS,
            CodecId::ADPCM_4XM => AV_CODEC_ID_ADPCM_4XM,
            CodecId::ADPCM_XA => AV_CODEC_ID_ADPCM_XA,
            CodecId::ADPCM_ADX => AV_CODEC_ID_ADPCM_ADX,
            CodecId::ADPCM_EA => AV_CODEC_ID_ADPCM_EA,
            CodecId::ADPCM_G726 => AV_CODEC_ID_ADPCM_G726,
            CodecId::ADPCM_CT => AV_CODEC_ID_ADPCM_CT,
            CodecId::ADPCM_SWF => AV_CODEC_ID_ADPCM_SWF,
            CodecId::ADPCM_YAMAHA => AV_CODEC_ID_ADPCM_YAMAHA,
            CodecId::ADPCM_SBPRO_4 => AV_CODEC_ID_ADPCM_SBPRO_4,
            CodecId::ADPCM_SBPRO_3 => AV_CODEC_ID_ADPCM_SBPRO_3,
            CodecId::ADPCM_SBPRO_2 => AV_CODEC_ID_ADPCM_SBPRO_2,
            CodecId::ADPCM_THP => AV_CODEC_ID_ADPCM_THP,
            CodecId::ADPCM_IMA_AMV => AV_CODEC_ID_ADPCM_IMA_AMV,
            CodecId::ADPCM_EA_R1 => AV_CODEC_ID_ADPCM_EA_R1,
            CodecId::ADPCM_EA_R3 => AV_CODEC_ID_ADPCM_EA_R3,
            CodecId::ADPCM_EA_R2 => AV_CODEC_ID_ADPCM_EA_R2,
            CodecId::ADPCM_IMA_EA_SEAD => AV_CODEC_ID_ADPCM_IMA_EA_SEAD,
            CodecId::ADPCM_IMA_EA_EACS => AV_CODEC_ID_ADPCM_IMA_EA_EACS,
            CodecId::ADPCM_EA_XAS => AV_CODEC_ID_ADPCM_EA_XAS,
            CodecId::ADPCM_EA_MAXIS_XA => AV_CODEC_ID_ADPCM_EA_MAXIS_XA,
            CodecId::ADPCM_IMA_ISS => AV_CODEC_ID_ADPCM_IMA_ISS,
            CodecId::ADPCM_G722 => AV_CODEC_ID_ADPCM_G722,
            CodecId::ADPCM_IMA_APC => AV_CODEC_ID_ADPCM_IMA_APC,
            CodecId::ADPCM_VIMA => AV_CODEC_ID_ADPCM_VIMA,
            CodecId::ADPCM_AFC => AV_CODEC_ID_ADPCM_AFC,
            CodecId::ADPCM_IMA_OKI => AV_CODEC_ID_ADPCM_IMA_OKI,
            CodecId::ADPCM_DTK => AV_CODEC_ID_ADPCM_DTK,
            CodecId::ADPCM_IMA_RAD => AV_CODEC_ID_ADPCM_IMA_RAD,
            CodecId::ADPCM_G726LE => AV_CODEC_ID_ADPCM_G726LE,
            CodecId::ADPCM_THP_LE => AV_CODEC_ID_ADPCM_THP_LE,
            CodecId::ADPCM_PSX => AV_CODEC_ID_ADPCM_PSX,
            CodecId::ADPCM_AICA => AV_CODEC_ID_ADPCM_AICA,
            CodecId::ADPCM_IMA_DAT4 => AV_CODEC_ID_ADPCM_IMA_DAT4,
            CodecId::ADPCM_MTAF => AV_CODEC_ID_ADPCM_MTAF,

            // AMR codecs
            CodecId::AMR_NB => AV_CODEC_ID_AMR_NB,
            CodecId::AMR_WB => AV_CODEC_ID_AMR_WB,

            // RealAudio codecs
            CodecId::RA_144 => AV_CODEC_ID_RA_144,
            CodecId::RA_288 => AV_CODEC_ID_RA_288,

            // DPCM codecs
            CodecId::ROQ_DPCM => AV_CODEC_ID_ROQ_DPCM,
            CodecId::INTERPLAY_DPCM => AV_CODEC_ID_INTERPLAY_DPCM,
            CodecId::XAN_DPCM => AV_CODEC_ID_XAN_DPCM,
            CodecId::SOL_DPCM => AV_CODEC_ID_SOL_DPCM,
            CodecId::SDX2_DPCM => AV_CODEC_ID_SDX2_DPCM,

            // Audio codecs
            CodecId::MP2 => AV_CODEC_ID_MP2,
            CodecId::MP3 => AV_CODEC_ID_MP3,
            CodecId::AAC => AV_CODEC_ID_AAC,
            CodecId::AC3 => AV_CODEC_ID_AC3,
            CodecId::DTS => AV_CODEC_ID_DTS,
            CodecId::VORBIS => AV_CODEC_ID_VORBIS,
            CodecId::DVAUDIO => AV_CODEC_ID_DVAUDIO,
            CodecId::WMAV1 => AV_CODEC_ID_WMAV1,
            CodecId::WMAV2 => AV_CODEC_ID_WMAV2,
            CodecId::MACE3 => AV_CODEC_ID_MACE3,
            CodecId::MACE6 => AV_CODEC_ID_MACE6,
            CodecId::VMDAUDIO => AV_CODEC_ID_VMDAUDIO,
            CodecId::FLAC => AV_CODEC_ID_FLAC,
            CodecId::MP3ADU => AV_CODEC_ID_MP3ADU,
            CodecId::MP3ON4 => AV_CODEC_ID_MP3ON4,
            CodecId::SHORTEN => AV_CODEC_ID_SHORTEN,
            CodecId::ALAC => AV_CODEC_ID_ALAC,
            CodecId::WESTWOOD_SND1 => AV_CODEC_ID_WESTWOOD_SND1,
            CodecId::GSM => AV_CODEC_ID_GSM,
            CodecId::QDM2 => AV_CODEC_ID_QDM2,
            CodecId::COOK => AV_CODEC_ID_COOK,
            CodecId::TRUESPEECH => AV_CODEC_ID_TRUESPEECH,
            CodecId::TTA => AV_CODEC_ID_TTA,
            CodecId::SMACKAUDIO => AV_CODEC_ID_SMACKAUDIO,
            CodecId::QCELP => AV_CODEC_ID_QCELP,
            CodecId::WAVPACK => AV_CODEC_ID_WAVPACK,
            CodecId::DSICINAUDIO => AV_CODEC_ID_DSICINAUDIO,
            CodecId::IMC => AV_CODEC_ID_IMC,
            CodecId::MUSEPACK7 => AV_CODEC_ID_MUSEPACK7,
            CodecId::MLP => AV_CODEC_ID_MLP,
            CodecId::GSM_MS => AV_CODEC_ID_GSM_MS,
            CodecId::ATRAC3 => AV_CODEC_ID_ATRAC3,
            CodecId::APE => AV_CODEC_ID_APE,
            CodecId::NELLYMOSER => AV_CODEC_ID_NELLYMOSER,
            CodecId::MUSEPACK8 => AV_CODEC_ID_MUSEPACK8,
            CodecId::SPEEX => AV_CODEC_ID_SPEEX,
            CodecId::WMAVOICE => AV_CODEC_ID_WMAVOICE,
            CodecId::WMAPRO => AV_CODEC_ID_WMAPRO,
            CodecId::WMALOSSLESS => AV_CODEC_ID_WMALOSSLESS,
            CodecId::ATRAC3P => AV_CODEC_ID_ATRAC3P,
            CodecId::EAC3 => AV_CODEC_ID_EAC3,
            CodecId::SIPR => AV_CODEC_ID_SIPR,
            CodecId::MP1 => AV_CODEC_ID_MP1,
            CodecId::TWINVQ => AV_CODEC_ID_TWINVQ,
            CodecId::TRUEHD => AV_CODEC_ID_TRUEHD,
            CodecId::MP4ALS => AV_CODEC_ID_MP4ALS,
            CodecId::ATRAC1 => AV_CODEC_ID_ATRAC1,
            CodecId::BINKAUDIO_RDFT => AV_CODEC_ID_BINKAUDIO_RDFT,
            CodecId::BINKAUDIO_DCT => AV_CODEC_ID_BINKAUDIO_DCT,
            CodecId::AAC_LATM => AV_CODEC_ID_AAC_LATM,
            CodecId::QDMC => AV_CODEC_ID_QDMC,
            CodecId::CELT => AV_CODEC_ID_CELT,
            CodecId::G723_1 => AV_CODEC_ID_G723_1,
            CodecId::G729 => AV_CODEC_ID_G729,
            CodecId::SVX_EXP8 => AV_CODEC_ID_8SVX_EXP,
            CodecId::SVX_FIB8 => AV_CODEC_ID_8SVX_FIB,
            CodecId::BMV_AUDIO => AV_CODEC_ID_BMV_AUDIO,
            CodecId::RALF => AV_CODEC_ID_RALF,
            CodecId::IAC => AV_CODEC_ID_IAC,
            CodecId::ILBC => AV_CODEC_ID_ILBC,
            CodecId::OPUS => AV_CODEC_ID_OPUS,
            CodecId::COMFORT_NOISE => AV_CODEC_ID_COMFORT_NOISE,
            CodecId::TAK => AV_CODEC_ID_TAK,
            CodecId::METASOUND => AV_CODEC_ID_METASOUND,
            CodecId::PAF_AUDIO => AV_CODEC_ID_PAF_AUDIO,
            CodecId::ON2AVC => AV_CODEC_ID_ON2AVC,
            CodecId::DSS_SP => AV_CODEC_ID_DSS_SP,
            CodecId::CODEC2 => AV_CODEC_ID_CODEC2,
            CodecId::FFWAVESYNTH => AV_CODEC_ID_FFWAVESYNTH,
            CodecId::SONIC => AV_CODEC_ID_SONIC,
            CodecId::SONIC_LS => AV_CODEC_ID_SONIC_LS,
            CodecId::EVRC => AV_CODEC_ID_EVRC,
            CodecId::SMV => AV_CODEC_ID_SMV,
            CodecId::DSD_LSBF => AV_CODEC_ID_DSD_LSBF,
            CodecId::DSD_MSBF => AV_CODEC_ID_DSD_MSBF,
            CodecId::DSD_LSBF_PLANAR => AV_CODEC_ID_DSD_LSBF_PLANAR,
            CodecId::DSD_MSBF_PLANAR => AV_CODEC_ID_DSD_MSBF_PLANAR,
            CodecId::_4GV => AV_CODEC_ID_4GV,
            CodecId::INTERPLAY_ACM => AV_CODEC_ID_INTERPLAY_ACM,
            CodecId::XMA1 => AV_CODEC_ID_XMA1,
            CodecId::XMA2 => AV_CODEC_ID_XMA2,
            CodecId::DST => AV_CODEC_ID_DST,

            // Subtitle codecs
            CodecId::DVD_SUBTITLE => AV_CODEC_ID_DVD_SUBTITLE,
            CodecId::DVB_SUBTITLE => AV_CODEC_ID_DVB_SUBTITLE,
            CodecId::TEXT => AV_CODEC_ID_TEXT,
            CodecId::XSUB => AV_CODEC_ID_XSUB,
            CodecId::SSA => AV_CODEC_ID_SSA,
            CodecId::MOV_TEXT => AV_CODEC_ID_MOV_TEXT,
            CodecId::HDMV_PGS_SUBTITLE => AV_CODEC_ID_HDMV_PGS_SUBTITLE,
            CodecId::DVB_TELETEXT => AV_CODEC_ID_DVB_TELETEXT,
            CodecId::SRT => AV_CODEC_ID_SRT,
            CodecId::MICRODVD => AV_CODEC_ID_MICRODVD,
            CodecId::EIA_608 => AV_CODEC_ID_EIA_608,
            CodecId::JACOSUB => AV_CODEC_ID_JACOSUB,
            CodecId::SAMI => AV_CODEC_ID_SAMI,
            CodecId::REALTEXT => AV_CODEC_ID_REALTEXT,
            CodecId::STL => AV_CODEC_ID_STL,
            CodecId::SUBVIEWER1 => AV_CODEC_ID_SUBVIEWER1,
            CodecId::SUBVIEWER => AV_CODEC_ID_SUBVIEWER,
            CodecId::SUBRIP => AV_CODEC_ID_SUBRIP,
            CodecId::WEBVTT => AV_CODEC_ID_WEBVTT,
            CodecId::MPL2 => AV_CODEC_ID_MPL2,
            CodecId::VPLAYER => AV_CODEC_ID_VPLAYER,
            CodecId::PJS => AV_CODEC_ID_PJS,
            CodecId::ASS => AV_CODEC_ID_ASS,
            CodecId::HDMV_TEXT_SUBTITLE => AV_CODEC_ID_HDMV_TEXT_SUBTITLE,

            // Other codecs
            CodecId::TTF => AV_CODEC_ID_TTF,
            CodecId::SCTE_35 => AV_CODEC_ID_SCTE_35,
            CodecId::BINTEXT => AV_CODEC_ID_BINTEXT,
            CodecId::XBIN => AV_CODEC_ID_XBIN,
            CodecId::IDF => AV_CODEC_ID_IDF,
            CodecId::OTF => AV_CODEC_ID_OTF,
            CodecId::SMPTE_KLV => AV_CODEC_ID_SMPTE_KLV,
            CodecId::DVD_NAV => AV_CODEC_ID_DVD_NAV,
            CodecId::TIMED_ID3 => AV_CODEC_ID_TIMED_ID3,
            CodecId::BIN_DATA => AV_CODEC_ID_BIN_DATA,
            CodecId::PROBE => AV_CODEC_ID_PROBE,
            CodecId::MPEG2TS => AV_CODEC_ID_MPEG2TS,
            CodecId::MPEG4SYSTEMS => AV_CODEC_ID_MPEG4SYSTEMS,
            CodecId::FFMETADATA => AV_CODEC_ID_FFMETADATA,
            CodecId::WRAPPED_AVFRAME => AV_CODEC_ID_WRAPPED_AVFRAME,
            CodecId::PSD => AV_CODEC_ID_PSD,
            CodecId::PIXLET => AV_CODEC_ID_PIXLET,
            CodecId::SPEEDHQ => AV_CODEC_ID_SPEEDHQ,
            CodecId::FMVC => AV_CODEC_ID_FMVC,
            CodecId::CLEARVIDEO => AV_CODEC_ID_CLEARVIDEO,
            CodecId::SCPR => AV_CODEC_ID_SCPR,
            CodecId::XPM => AV_CODEC_ID_XPM,
            CodecId::AV1 => AV_CODEC_ID_AV1,
            CodecId::PCM_F16LE => AV_CODEC_ID_PCM_F16LE,
            CodecId::PCM_F24LE => AV_CODEC_ID_PCM_F24LE,
            CodecId::ATRAC3AL => AV_CODEC_ID_ATRAC3AL,
            CodecId::ATRAC3PAL => AV_CODEC_ID_ATRAC3PAL,
            CodecId::BITPACKED => AV_CODEC_ID_BITPACKED,
            CodecId::MSCC => AV_CODEC_ID_MSCC,
            CodecId::SRGC => AV_CODEC_ID_SRGC,
            CodecId::SVG => AV_CODEC_ID_SVG,
            CodecId::GDV => AV_CODEC_ID_GDV,
            CodecId::FITS => AV_CODEC_ID_FITS,
            CodecId::GREMLIN_DPCM => AV_CODEC_ID_GREMLIN_DPCM,
            CodecId::DOLBY_E => AV_CODEC_ID_DOLBY_E,
            CodecId::APTX => AV_CODEC_ID_APTX,
            CodecId::APTX_HD => AV_CODEC_ID_APTX_HD,
            CodecId::SBC => AV_CODEC_ID_SBC,
            CodecId::AVS2 => AV_CODEC_ID_AVS2,
            CodecId::IMM4 => AV_CODEC_ID_IMM4,
            CodecId::PROSUMER => AV_CODEC_ID_PROSUMER,
            CodecId::MWSC => AV_CODEC_ID_MWSC,
            CodecId::WCMV => AV_CODEC_ID_WCMV,
            CodecId::RASC => AV_CODEC_ID_RASC,
            CodecId::PCM_VIDC => AV_CODEC_ID_PCM_VIDC,
            CodecId::ATRAC9 => AV_CODEC_ID_ATRAC9,
            CodecId::TTML => AV_CODEC_ID_TTML,
            CodecId::HYMT => AV_CODEC_ID_HYMT,
            CodecId::ARBC => AV_CODEC_ID_ARBC,
            CodecId::AGM => AV_CODEC_ID_AGM,
            CodecId::LSCR => AV_CODEC_ID_LSCR,
            CodecId::VP4 => AV_CODEC_ID_VP4,
            CodecId::ADPCM_AGM => AV_CODEC_ID_ADPCM_AGM,
            CodecId::HCOM => AV_CODEC_ID_HCOM,
            CodecId::ARIB_CAPTION => AV_CODEC_ID_ARIB_CAPTION,
            CodecId::IMM5 => AV_CODEC_ID_IMM5,
            CodecId::MVDV => AV_CODEC_ID_MVDV,
            CodecId::MVHA => AV_CODEC_ID_MVHA,
            CodecId::CDTOONS => AV_CODEC_ID_CDTOONS,
            CodecId::MV30 => AV_CODEC_ID_MV30,
            CodecId::NOTCHLC => AV_CODEC_ID_NOTCHLC,
            CodecId::PFM => AV_CODEC_ID_PFM,
            CodecId::ADPCM_ARGO => AV_CODEC_ID_ADPCM_ARGO,
            CodecId::ADPCM_IMA_SSI => AV_CODEC_ID_ADPCM_IMA_SSI,
            CodecId::ADPCM_ZORK => AV_CODEC_ID_ADPCM_ZORK,
            CodecId::ADPCM_IMA_APM => AV_CODEC_ID_ADPCM_IMA_APM,
            CodecId::ADPCM_IMA_ALP => AV_CODEC_ID_ADPCM_IMA_ALP,
            CodecId::ADPCM_IMA_MTF => AV_CODEC_ID_ADPCM_IMA_MTF,
            CodecId::ADPCM_IMA_CUNNING => AV_CODEC_ID_ADPCM_IMA_CUNNING,
            CodecId::DERF_DPCM => AV_CODEC_ID_DERF_DPCM,
            CodecId::ACELP_KELVIN => AV_CODEC_ID_ACELP_KELVIN,
            CodecId::MPEGH_3D_AUDIO => AV_CODEC_ID_MPEGH_3D_AUDIO,
            CodecId::SIREN => AV_CODEC_ID_SIREN,
            CodecId::HCA => AV_CODEC_ID_HCA,
            CodecId::EPG => AV_CODEC_ID_EPG,
            CodecId::PGX => AV_CODEC_ID_PGX,
            CodecId::AVS3 => AV_CODEC_ID_AVS3,
            CodecId::MSP2 => AV_CODEC_ID_MSP2,
            CodecId::VVC => AV_CODEC_ID_VVC,
            CodecId::MOBICLIP => AV_CODEC_ID_MOBICLIP,
            CodecId::PHOTOCD => AV_CODEC_ID_PHOTOCD,
            CodecId::IPU => AV_CODEC_ID_IPU,
            CodecId::ARGO => AV_CODEC_ID_ARGO,
            CodecId::CRI => AV_CODEC_ID_CRI,
            CodecId::SIMBIOSIS_IMX => AV_CODEC_ID_SIMBIOSIS_IMX,
            CodecId::SGA_VIDEO => AV_CODEC_ID_SGA_VIDEO,
            CodecId::PCM_SGA => AV_CODEC_ID_PCM_SGA,
            CodecId::ADPCM_IMA_MOFLEX => AV_CODEC_ID_ADPCM_IMA_MOFLEX,
            CodecId::FASTAUDIO => AV_CODEC_ID_FASTAUDIO,
            CodecId::GEM => AV_CODEC_ID_GEM,
            CodecId::ADPCM_IMA_ACORN => AV_CODEC_ID_ADPCM_IMA_ACORN,
            CodecId::MSNSIREN => AV_CODEC_ID_MSNSIREN,
            CodecId::VBN => AV_CODEC_ID_VBN,
            CodecId::JPEGXL => AV_CODEC_ID_JPEGXL,
            CodecId::QOI => AV_CODEC_ID_QOI,
            CodecId::PHM => AV_CODEC_ID_PHM,
            CodecId::DFPWM => AV_CODEC_ID_DFPWM,
            CodecId::RADIANCE_HDR => AV_CODEC_ID_RADIANCE_HDR,
            CodecId::WBMP => AV_CODEC_ID_WBMP,
            CodecId::MEDIA100 => AV_CODEC_ID_MEDIA100,
            CodecId::VQC => AV_CODEC_ID_VQC,
            CodecId::ADPCM_XMD => AV_CODEC_ID_ADPCM_XMD,
            CodecId::WADY_DPCM => AV_CODEC_ID_WADY_DPCM,
            CodecId::CBD2_DPCM => AV_CODEC_ID_CBD2_DPCM,
            CodecId::BONK => AV_CODEC_ID_BONK,
            CodecId::MISC4 => AV_CODEC_ID_MISC4,
            CodecId::APAC => AV_CODEC_ID_APAC,
            CodecId::FTR => AV_CODEC_ID_FTR,
            CodecId::WAVARC => AV_CODEC_ID_WAVARC,
            CodecId::RKA => AV_CODEC_ID_RKA,
            CodecId::VNULL => AV_CODEC_ID_VNULL,
            CodecId::ANULL => AV_CODEC_ID_ANULL,
            CodecId::PDV => AV_CODEC_ID_PDV,
            CodecId::EVC => AV_CODEC_ID_EVC,
            CodecId::RTV1 => AV_CODEC_ID_RTV1,
            CodecId::VMIX => AV_CODEC_ID_VMIX,
            CodecId::AC4 => AV_CODEC_ID_AC4,
            CodecId::SMPTE_2038 => AV_CODEC_ID_SMPTE_2038,
            CodecId::OSQ => AV_CODEC_ID_OSQ,

            CodecId::LEAD => AV_CODEC_ID_LEAD,
            CodecId::QOA => AV_CODEC_ID_QOA,
        }
    }
}
