use std::str::FromStr;

use crate::ffi;

#[allow(non_camel_case_types)]
#[derive(Eq, PartialEq, Copy, Clone, Debug)]
pub enum PixelFormat {
    None,

    YUV420P,
    YUYV422,
    RGB24,
    BGR24,
    YUV422P,
    YUV444P,
    YUV410P,
    YUV411P,
    GRAY8,
    MonoWhite,
    MonoBlack,
    PAL8,
    YUVJ420P,
    YUVJ422P,
    YUVJ444P,
    UYVY422,
    UYYVYY411,
    BGR8,
    BGR4,
    BGR4_BYTE,
    RGB8,
    RGB4,
    RGB4_BYTE,
    NV12,
    NV21,
    ARGB,
    RGBA,
    ABGR,
    BGRA,
    GRAY16BE,
    GRAY16LE,
    YUV440P,
    YUVJ440P,
    YUVA420P,
    RGB48BE,
    RGB48LE,
    RGB565BE,
    RGB565LE,
    RGB555BE,
    RGB555LE,
    BGR565BE,
    BGR565LE,
    BGR555BE,
    BGR555LE,
    VAAPI,
    YUV420P16LE,
    YUV420P16BE,
    YUV422P16LE,
    YUV422P16BE,
    YUV444P16LE,
    YUV444P16BE,
    DXVA2_VLD,
    RGB444LE,
    RGB444BE,
    BGR444LE,
    BGR444BE,
    YA8,
    BGR48BE,
    BGR48LE,
    YUV420P9BE,
    YUV420P9LE,
    YUV420P10BE,
    YUV420P10LE,
    YUV422P10BE,
    YUV422P10LE,
    YUV444P9BE,
    YUV444P9LE,
    YUV444P10BE,
    YUV444P10LE,
    YUV422P9BE,
    YUV422P9LE,
    GBRP,
    GBRP9BE,
    GBRP9LE,
    GBRP10BE,
    GBRP10LE,
    GBRP16BE,
    GBRP16LE,
    YUVA420P9BE,
    YUVA420P9LE,
    YUVA422P9BE,
    YUVA422P9LE,
    YUVA444P9BE,
    YUVA444P9LE,
    YUVA420P10BE,
    YUVA420P10LE,
    YUVA422P10BE,
    YUVA422P10LE,
    YUVA444P10BE,
    YUVA444P10LE,
    YUVA420P16BE,
    YUVA420P16LE,
    YUVA422P16BE,
    YUVA422P16LE,
    YUVA444P16BE,
    YUVA444P16LE,
    VDPAU,
    XYZ12LE,
    XYZ12BE,
    NV16,
    NV20LE,
    NV20BE,
    RGBA64BE,
    RGBA64LE,
    BGRA64BE,
    BGRA64LE,
    YVYU422,
    YA16BE,
    YA16LE,
    QSV,
    MMAL,
    D3D11VA_VLD,
    CUDA,
    ZRGB,
    RGBZ,
    ZBGR,
    BGRZ,
    YUVA444P,
    YUVA422P,
    YUV420P12BE,
    YUV420P12LE,
    YUV420P14BE,
    YUV420P14LE,
    YUV422P12BE,
    YUV422P12LE,
    YUV422P14BE,
    YUV422P14LE,
    YUV444P12BE,
    YUV444P12LE,
    YUV444P14BE,
    YUV444P14LE,
    GBRP12BE,
    GBRP12LE,
    GBRP14BE,
    GBRP14LE,
    GBRAP,
    GBRAP16BE,
    GBRAP16LE,
    YUVJ411P,
    BAYER_BGGR8,
    BAYER_RGGB8,
    BAYER_GBRG8,
    BAYER_GRBG8,
    BAYER_BGGR16LE,
    BAYER_BGGR16BE,
    BAYER_RGGB16LE,
    BAYER_RGGB16BE,
    BAYER_GBRG16LE,
    BAYER_GBRG16BE,
    BAYER_GRBG16LE,
    BAYER_GRBG16BE,
    YUV440P10LE,
    YUV440P10BE,
    YUV440P12LE,
    YUV440P12BE,
    AYUV64LE,
    AYUV64BE,
    VIDEOTOOLBOX,
    RGB32,
    RGB32_1,
    BGR32,
    BGR32_1,
    ZRGB32,
    ZBGR32,
    GRAY16,
    YA16,
    RGB48,
    RGB565,
    RGB555,
    RGB444,
    BGR48,
    BGR565,
    BGR555,
    BGR444,
    YUV420P9,
    YUV422P9,
    YUV444P9,
    YUV420P10,
    YUV422P10,
    YUV440P10,
    YUV444P10,
    YUV420P12,
    YUV422P12,
    YUV440P12,
    YUV444P12,
    YUV420P14,
    YUV422P14,
    YUV444P14,
    YUV420P16,
    YUV422P16,
    YUV444P16,
    GBRP9,
    GBRP10,
    GBRP12,
    GBRP14,
    GBRP16,
    GBRAP16,
    BAYER_BGGR16,
    BAYER_RGGB16,
    BAYER_GBRG16,
    BAYER_GRBG16,
    YUVA420P9,
    YUVA422P9,
    YUVA444P9,
    YUVA420P10,
    YUVA422P10,
    YUVA444P10,
    YUVA420P16,
    YUVA422P16,
    YUVA444P16,
    XYZ12,
    NV20,
    AYUV64,
    P010LE,
    P010BE,
    GBRAP12BE,
    GBRAP12LE,
    GBRAP10LE,
    GBRAP10BE,
    MEDIACODEC,
    GRAY12BE,
    GRAY12LE,
    GRAY10BE,
    GRAY10LE,
    P016LE,
    P016BE,
    D3D11,
    GRAY9BE,
    GRAY9LE,
    GBRPF32BE,
    GBRPF32LE,
    GBRAPF32BE,
    GBRAPF32LE,
    DRM_PRIME,
    OPENCL,
    GRAY14BE,
    GRAY14LE,
    GRAYF32BE,
    GRAYF32LE,
    YUVA422P12BE,
    YUVA422P12LE,
    YUVA444P12BE,
    YUVA444P12LE,
    NV24,
    NV42,
    VULKAN,
    Y210BE,
    Y210LE,
    X2RGB10LE,
    X2RGB10BE,
    X2BGR10LE,
    X2BGR10BE,
    P210BE,
    P210LE,
    P410BE,
    P410LE,
    P216BE,
    P216LE,
    P416BE,
    P416LE,
    VUYA,
    RGBAF16BE,
    RGBAF16LE,
    VUYX,
    P012LE,
    P012BE,
    Y212BE,
    Y212LE,
    XV30BE,
    XV30LE,
    XV36BE,
    XV36LE,
    RGBF32BE,
    RGBF32LE,
    RGBAF32BE,
    RGBAF32LE,
    P212BE,
    P212LE,
    P412BE,
    P412LE,
    GBRAP14BE,
    GBRAP14LE,
    D3D12,
}

impl From<ffi::AVPixelFormat> for PixelFormat {
    #[inline]
    fn from(pixel: ffi::AVPixelFormat) -> Self {
        match pixel {
            ffi::AVPixelFormat::AV_PIX_FMT_NONE => PixelFormat::None,

            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P => PixelFormat::YUV420P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUYV422 => PixelFormat::YUYV422,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB24 => PixelFormat::RGB24,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR24 => PixelFormat::BGR24,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P => PixelFormat::YUV422P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P => PixelFormat::YUV444P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV410P => PixelFormat::YUV410P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV411P => PixelFormat::YUV411P,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY8 => PixelFormat::GRAY8,
            ffi::AVPixelFormat::AV_PIX_FMT_MONOWHITE => PixelFormat::MonoWhite,
            ffi::AVPixelFormat::AV_PIX_FMT_MONOBLACK => PixelFormat::MonoBlack,
            ffi::AVPixelFormat::AV_PIX_FMT_PAL8 => PixelFormat::PAL8,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVJ420P => PixelFormat::YUVJ420P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVJ422P => PixelFormat::YUVJ422P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVJ444P => PixelFormat::YUVJ444P,
            ffi::AVPixelFormat::AV_PIX_FMT_UYVY422 => PixelFormat::UYVY422,
            ffi::AVPixelFormat::AV_PIX_FMT_UYYVYY411 => PixelFormat::UYYVYY411,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR8 => PixelFormat::BGR8,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR4 => PixelFormat::BGR4,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR4_BYTE => PixelFormat::BGR4_BYTE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB8 => PixelFormat::RGB8,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB4 => PixelFormat::RGB4,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB4_BYTE => PixelFormat::RGB4_BYTE,
            ffi::AVPixelFormat::AV_PIX_FMT_NV12 => PixelFormat::NV12,
            ffi::AVPixelFormat::AV_PIX_FMT_NV21 => PixelFormat::NV21,
            ffi::AVPixelFormat::AV_PIX_FMT_ARGB => PixelFormat::ARGB,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBA => PixelFormat::RGBA,
            ffi::AVPixelFormat::AV_PIX_FMT_ABGR => PixelFormat::ABGR,
            ffi::AVPixelFormat::AV_PIX_FMT_BGRA => PixelFormat::BGRA,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY16BE => PixelFormat::GRAY16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY16LE => PixelFormat::GRAY16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV440P => PixelFormat::YUV440P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVJ440P => PixelFormat::YUVJ440P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P => PixelFormat::YUVA420P,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB48BE => PixelFormat::RGB48BE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB48LE => PixelFormat::RGB48LE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB565BE => PixelFormat::RGB565BE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB565LE => PixelFormat::RGB565LE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB555BE => PixelFormat::RGB555BE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB555LE => PixelFormat::RGB555LE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR565BE => PixelFormat::BGR565BE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR565LE => PixelFormat::BGR565LE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR555BE => PixelFormat::BGR555BE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR555LE => PixelFormat::BGR555LE,
            ffi::AVPixelFormat::AV_PIX_FMT_VAAPI => PixelFormat::VAAPI,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P16LE => PixelFormat::YUV420P16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P16BE => PixelFormat::YUV420P16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P16LE => PixelFormat::YUV422P16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P16BE => PixelFormat::YUV422P16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P16LE => PixelFormat::YUV444P16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P16BE => PixelFormat::YUV444P16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_DXVA2_VLD => PixelFormat::DXVA2_VLD,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB444LE => PixelFormat::RGB444LE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB444BE => PixelFormat::RGB444BE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR444LE => PixelFormat::BGR444LE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR444BE => PixelFormat::BGR444BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YA8 => PixelFormat::YA8,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR48BE => PixelFormat::BGR48BE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR48LE => PixelFormat::BGR48LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P9BE => PixelFormat::YUV420P9BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P9LE => PixelFormat::YUV420P9LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P10BE => PixelFormat::YUV420P10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P10LE => PixelFormat::YUV420P10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P10BE => PixelFormat::YUV422P10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P10LE => PixelFormat::YUV422P10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P9BE => PixelFormat::YUV444P9BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P9LE => PixelFormat::YUV444P9LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P10BE => PixelFormat::YUV444P10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P10LE => PixelFormat::YUV444P10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P9BE => PixelFormat::YUV422P9BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P9LE => PixelFormat::YUV422P9LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP => PixelFormat::GBRP,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP9BE => PixelFormat::GBRP9BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP9LE => PixelFormat::GBRP9LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP10BE => PixelFormat::GBRP10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP10LE => PixelFormat::GBRP10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP16BE => PixelFormat::GBRP16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP16LE => PixelFormat::GBRP16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P9BE => PixelFormat::YUVA420P9BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P9LE => PixelFormat::YUVA420P9LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P9BE => PixelFormat::YUVA422P9BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P9LE => PixelFormat::YUVA422P9LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P9BE => PixelFormat::YUVA444P9BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P9LE => PixelFormat::YUVA444P9LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P10BE => PixelFormat::YUVA420P10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P10LE => PixelFormat::YUVA420P10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P10BE => PixelFormat::YUVA422P10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P10LE => PixelFormat::YUVA422P10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P10BE => PixelFormat::YUVA444P10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P10LE => PixelFormat::YUVA444P10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P16BE => PixelFormat::YUVA420P16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P16LE => PixelFormat::YUVA420P16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P16BE => PixelFormat::YUVA422P16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P16LE => PixelFormat::YUVA422P16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P16BE => PixelFormat::YUVA444P16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P16LE => PixelFormat::YUVA444P16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_VDPAU => PixelFormat::VDPAU,
            ffi::AVPixelFormat::AV_PIX_FMT_XYZ12LE => PixelFormat::XYZ12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_XYZ12BE => PixelFormat::XYZ12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_NV16 => PixelFormat::NV16,
            ffi::AVPixelFormat::AV_PIX_FMT_NV20LE => PixelFormat::NV20LE,
            ffi::AVPixelFormat::AV_PIX_FMT_NV20BE => PixelFormat::NV20BE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBA64BE => PixelFormat::RGBA64BE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBA64LE => PixelFormat::RGBA64LE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGRA64BE => PixelFormat::BGRA64BE,
            ffi::AVPixelFormat::AV_PIX_FMT_BGRA64LE => PixelFormat::BGRA64LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YVYU422 => PixelFormat::YVYU422,
            ffi::AVPixelFormat::AV_PIX_FMT_YA16BE => PixelFormat::YA16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YA16LE => PixelFormat::YA16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_QSV => PixelFormat::QSV,
            ffi::AVPixelFormat::AV_PIX_FMT_MMAL => PixelFormat::MMAL,
            ffi::AVPixelFormat::AV_PIX_FMT_D3D11VA_VLD => PixelFormat::D3D11VA_VLD,
            ffi::AVPixelFormat::AV_PIX_FMT_CUDA => PixelFormat::CUDA,
            ffi::AVPixelFormat::AV_PIX_FMT_0RGB => PixelFormat::ZRGB,
            ffi::AVPixelFormat::AV_PIX_FMT_RGB0 => PixelFormat::RGBZ,
            ffi::AVPixelFormat::AV_PIX_FMT_0BGR => PixelFormat::ZBGR,
            ffi::AVPixelFormat::AV_PIX_FMT_BGR0 => PixelFormat::BGRZ,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P => PixelFormat::YUVA444P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P => PixelFormat::YUVA422P,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P12BE => PixelFormat::YUV420P12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P12LE => PixelFormat::YUV420P12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P14BE => PixelFormat::YUV420P14BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV420P14LE => PixelFormat::YUV420P14LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P12BE => PixelFormat::YUV422P12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P12LE => PixelFormat::YUV422P12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P14BE => PixelFormat::YUV422P14BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV422P14LE => PixelFormat::YUV422P14LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P12BE => PixelFormat::YUV444P12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P12LE => PixelFormat::YUV444P12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P14BE => PixelFormat::YUV444P14BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV444P14LE => PixelFormat::YUV444P14LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP12BE => PixelFormat::GBRP12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP12LE => PixelFormat::GBRP12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP14BE => PixelFormat::GBRP14BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRP14LE => PixelFormat::GBRP14LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP => PixelFormat::GBRAP,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP16BE => PixelFormat::GBRAP16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP16LE => PixelFormat::GBRAP16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVJ411P => PixelFormat::YUVJ411P,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_BGGR8 => PixelFormat::BAYER_BGGR8,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_RGGB8 => PixelFormat::BAYER_RGGB8,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GBRG8 => PixelFormat::BAYER_GBRG8,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GRBG8 => PixelFormat::BAYER_GRBG8,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_BGGR16LE => PixelFormat::BAYER_BGGR16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_BGGR16BE => PixelFormat::BAYER_BGGR16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_RGGB16LE => PixelFormat::BAYER_RGGB16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_RGGB16BE => PixelFormat::BAYER_RGGB16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GBRG16LE => PixelFormat::BAYER_GBRG16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GBRG16BE => PixelFormat::BAYER_GBRG16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GRBG16LE => PixelFormat::BAYER_GRBG16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GRBG16BE => PixelFormat::BAYER_GRBG16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV440P10LE => PixelFormat::YUV440P10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV440P10BE => PixelFormat::YUV440P10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV440P12LE => PixelFormat::YUV440P12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUV440P12BE => PixelFormat::YUV440P12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_AYUV64LE => PixelFormat::AYUV64LE,
            ffi::AVPixelFormat::AV_PIX_FMT_AYUV64BE => PixelFormat::AYUV64BE,
            ffi::AVPixelFormat::AV_PIX_FMT_VIDEOTOOLBOX => PixelFormat::VIDEOTOOLBOX,
            ffi::AVPixelFormat::AV_PIX_FMT_P010LE => PixelFormat::P010LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P010BE => PixelFormat::P010BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP12BE => PixelFormat::GBRAP12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP12LE => PixelFormat::GBRAP12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP10LE => PixelFormat::GBRAP10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP10BE => PixelFormat::GBRAP10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_MEDIACODEC => PixelFormat::MEDIACODEC,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY12BE => PixelFormat::GRAY12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY12LE => PixelFormat::GRAY12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY10BE => PixelFormat::GRAY10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY10LE => PixelFormat::GRAY10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P016LE => PixelFormat::P016LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P016BE => PixelFormat::P016BE,
            ffi::AVPixelFormat::AV_PIX_FMT_NB => PixelFormat::None,
            ffi::AVPixelFormat::AV_PIX_FMT_D3D11 => PixelFormat::D3D11,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY9BE => PixelFormat::GRAY9BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY9LE => PixelFormat::GRAY9LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRPF32BE => PixelFormat::GBRPF32BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRPF32LE => PixelFormat::GBRPF32LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAPF32BE => PixelFormat::GBRAPF32BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAPF32LE => PixelFormat::GBRAPF32LE,
            ffi::AVPixelFormat::AV_PIX_FMT_DRM_PRIME => PixelFormat::DRM_PRIME,
            ffi::AVPixelFormat::AV_PIX_FMT_OPENCL => PixelFormat::OPENCL,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY14BE => PixelFormat::GRAY14BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAY14LE => PixelFormat::GRAY14LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAYF32BE => PixelFormat::GRAYF32BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GRAYF32LE => PixelFormat::GRAYF32LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P12BE => PixelFormat::YUVA422P12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P12LE => PixelFormat::YUVA422P12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P12BE => PixelFormat::YUVA444P12BE,
            ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P12LE => PixelFormat::YUVA444P12LE,
            ffi::AVPixelFormat::AV_PIX_FMT_NV24 => PixelFormat::NV24,
            ffi::AVPixelFormat::AV_PIX_FMT_NV42 => PixelFormat::NV42,
            ffi::AVPixelFormat::AV_PIX_FMT_VULKAN => PixelFormat::VULKAN,
            ffi::AVPixelFormat::AV_PIX_FMT_Y210BE => PixelFormat::Y210BE,
            ffi::AVPixelFormat::AV_PIX_FMT_Y210LE => PixelFormat::Y210LE,
            ffi::AVPixelFormat::AV_PIX_FMT_X2RGB10LE => PixelFormat::X2RGB10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_X2RGB10BE => PixelFormat::X2RGB10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_X2BGR10LE => PixelFormat::X2BGR10LE,
            ffi::AVPixelFormat::AV_PIX_FMT_X2BGR10BE => PixelFormat::X2BGR10BE,
            ffi::AVPixelFormat::AV_PIX_FMT_P210BE => PixelFormat::P210BE,
            ffi::AVPixelFormat::AV_PIX_FMT_P210LE => PixelFormat::P210LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P410BE => PixelFormat::P410BE,
            ffi::AVPixelFormat::AV_PIX_FMT_P410LE => PixelFormat::P410LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P216BE => PixelFormat::P216BE,
            ffi::AVPixelFormat::AV_PIX_FMT_P216LE => PixelFormat::P216LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P416BE => PixelFormat::P416BE,
            ffi::AVPixelFormat::AV_PIX_FMT_P416LE => PixelFormat::P416LE,
            ffi::AVPixelFormat::AV_PIX_FMT_VUYA => PixelFormat::VUYA,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBAF16BE => PixelFormat::RGBAF16BE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBAF16LE => PixelFormat::RGBAF16LE,
            ffi::AVPixelFormat::AV_PIX_FMT_VUYX => PixelFormat::VUYX,
            ffi::AVPixelFormat::AV_PIX_FMT_P012LE => PixelFormat::P012LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P012BE => PixelFormat::P012BE,
            ffi::AVPixelFormat::AV_PIX_FMT_Y212BE => PixelFormat::Y212BE,
            ffi::AVPixelFormat::AV_PIX_FMT_Y212LE => PixelFormat::Y212LE,
            ffi::AVPixelFormat::AV_PIX_FMT_XV30BE => PixelFormat::XV30BE,
            ffi::AVPixelFormat::AV_PIX_FMT_XV30LE => PixelFormat::XV30LE,
            ffi::AVPixelFormat::AV_PIX_FMT_XV36BE => PixelFormat::XV36BE,
            ffi::AVPixelFormat::AV_PIX_FMT_XV36LE => PixelFormat::XV36LE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBF32BE => PixelFormat::RGBF32BE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBF32LE => PixelFormat::RGBF32LE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBAF32BE => PixelFormat::RGBAF32BE,
            ffi::AVPixelFormat::AV_PIX_FMT_RGBAF32LE => PixelFormat::RGBAF32LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P212BE => PixelFormat::P212BE,
            ffi::AVPixelFormat::AV_PIX_FMT_P212LE => PixelFormat::P212LE,
            ffi::AVPixelFormat::AV_PIX_FMT_P412BE => PixelFormat::P412BE,
            ffi::AVPixelFormat::AV_PIX_FMT_P412LE => PixelFormat::P412LE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP14BE => PixelFormat::GBRAP14BE,
            ffi::AVPixelFormat::AV_PIX_FMT_GBRAP14LE => PixelFormat::GBRAP14LE,
            ffi::AVPixelFormat::AV_PIX_FMT_D3D12 => PixelFormat::D3D12,
        }
    }
}

impl From<PixelFormat> for ffi::AVPixelFormat {
    #[inline]
    fn from(pixel: PixelFormat) -> ffi::AVPixelFormat {
        match pixel {
            PixelFormat::None => ffi::AVPixelFormat::AV_PIX_FMT_NONE,

            PixelFormat::YUV420P => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P,
            PixelFormat::YUYV422 => ffi::AVPixelFormat::AV_PIX_FMT_YUYV422,
            PixelFormat::RGB24 => ffi::AVPixelFormat::AV_PIX_FMT_RGB24,
            PixelFormat::BGR24 => ffi::AVPixelFormat::AV_PIX_FMT_BGR24,
            PixelFormat::YUV422P => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P,
            PixelFormat::YUV444P => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P,
            PixelFormat::YUV410P => ffi::AVPixelFormat::AV_PIX_FMT_YUV410P,
            PixelFormat::YUV411P => ffi::AVPixelFormat::AV_PIX_FMT_YUV411P,
            PixelFormat::GRAY8 => ffi::AVPixelFormat::AV_PIX_FMT_GRAY8,
            PixelFormat::MonoWhite => ffi::AVPixelFormat::AV_PIX_FMT_MONOWHITE,
            PixelFormat::MonoBlack => ffi::AVPixelFormat::AV_PIX_FMT_MONOBLACK,
            PixelFormat::PAL8 => ffi::AVPixelFormat::AV_PIX_FMT_PAL8,
            PixelFormat::YUVJ420P => ffi::AVPixelFormat::AV_PIX_FMT_YUVJ420P,
            PixelFormat::YUVJ422P => ffi::AVPixelFormat::AV_PIX_FMT_YUVJ422P,
            PixelFormat::YUVJ444P => ffi::AVPixelFormat::AV_PIX_FMT_YUVJ444P,
            PixelFormat::UYVY422 => ffi::AVPixelFormat::AV_PIX_FMT_UYVY422,
            PixelFormat::UYYVYY411 => ffi::AVPixelFormat::AV_PIX_FMT_UYYVYY411,
            PixelFormat::BGR8 => ffi::AVPixelFormat::AV_PIX_FMT_BGR8,
            PixelFormat::BGR4 => ffi::AVPixelFormat::AV_PIX_FMT_BGR4,
            PixelFormat::BGR4_BYTE => ffi::AVPixelFormat::AV_PIX_FMT_BGR4_BYTE,
            PixelFormat::RGB8 => ffi::AVPixelFormat::AV_PIX_FMT_RGB8,
            PixelFormat::RGB4 => ffi::AVPixelFormat::AV_PIX_FMT_RGB4,
            PixelFormat::RGB4_BYTE => ffi::AVPixelFormat::AV_PIX_FMT_RGB4_BYTE,
            PixelFormat::NV12 => ffi::AVPixelFormat::AV_PIX_FMT_NV12,
            PixelFormat::NV21 => ffi::AVPixelFormat::AV_PIX_FMT_NV21,
            PixelFormat::ARGB => ffi::AVPixelFormat::AV_PIX_FMT_ARGB,
            PixelFormat::RGBA => ffi::AVPixelFormat::AV_PIX_FMT_RGBA,
            PixelFormat::ABGR => ffi::AVPixelFormat::AV_PIX_FMT_ABGR,
            PixelFormat::BGRA => ffi::AVPixelFormat::AV_PIX_FMT_BGRA,
            PixelFormat::GRAY16BE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY16BE,
            PixelFormat::GRAY16LE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY16LE,
            PixelFormat::YUV440P => ffi::AVPixelFormat::AV_PIX_FMT_YUV440P,
            PixelFormat::YUVJ440P => ffi::AVPixelFormat::AV_PIX_FMT_YUVJ440P,
            PixelFormat::YUVA420P => ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P,
            PixelFormat::RGB48BE => ffi::AVPixelFormat::AV_PIX_FMT_RGB48BE,
            PixelFormat::RGB48LE => ffi::AVPixelFormat::AV_PIX_FMT_RGB48LE,
            PixelFormat::RGB565BE => ffi::AVPixelFormat::AV_PIX_FMT_RGB565BE,
            PixelFormat::RGB565LE => ffi::AVPixelFormat::AV_PIX_FMT_RGB565LE,
            PixelFormat::RGB555BE => ffi::AVPixelFormat::AV_PIX_FMT_RGB555BE,
            PixelFormat::RGB555LE => ffi::AVPixelFormat::AV_PIX_FMT_RGB555LE,
            PixelFormat::BGR565BE => ffi::AVPixelFormat::AV_PIX_FMT_BGR565BE,
            PixelFormat::BGR565LE => ffi::AVPixelFormat::AV_PIX_FMT_BGR565LE,
            PixelFormat::BGR555BE => ffi::AVPixelFormat::AV_PIX_FMT_BGR555BE,
            PixelFormat::BGR555LE => ffi::AVPixelFormat::AV_PIX_FMT_BGR555LE,
            PixelFormat::VAAPI => ffi::AVPixelFormat::AV_PIX_FMT_VAAPI,
            PixelFormat::YUV420P16LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P16LE,
            PixelFormat::YUV420P16BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P16BE,
            PixelFormat::YUV422P16LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P16LE,
            PixelFormat::YUV422P16BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P16BE,
            PixelFormat::YUV444P16LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P16LE,
            PixelFormat::YUV444P16BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P16BE,
            PixelFormat::DXVA2_VLD => ffi::AVPixelFormat::AV_PIX_FMT_DXVA2_VLD,
            PixelFormat::RGB444LE => ffi::AVPixelFormat::AV_PIX_FMT_RGB444LE,
            PixelFormat::RGB444BE => ffi::AVPixelFormat::AV_PIX_FMT_RGB444BE,
            PixelFormat::BGR444LE => ffi::AVPixelFormat::AV_PIX_FMT_BGR444LE,
            PixelFormat::BGR444BE => ffi::AVPixelFormat::AV_PIX_FMT_BGR444BE,
            PixelFormat::YA8 => ffi::AVPixelFormat::AV_PIX_FMT_YA8,
            PixelFormat::BGR48BE => ffi::AVPixelFormat::AV_PIX_FMT_BGR48BE,
            PixelFormat::BGR48LE => ffi::AVPixelFormat::AV_PIX_FMT_BGR48LE,
            PixelFormat::YUV420P9BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P9BE,
            PixelFormat::YUV420P9LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P9LE,
            PixelFormat::YUV420P10BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P10BE,
            PixelFormat::YUV420P10LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P10LE,
            PixelFormat::YUV422P10BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P10BE,
            PixelFormat::YUV422P10LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P10LE,
            PixelFormat::YUV444P9BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P9BE,
            PixelFormat::YUV444P9LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P9LE,
            PixelFormat::YUV444P10BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P10BE,
            PixelFormat::YUV444P10LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P10LE,
            PixelFormat::YUV422P9BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P9BE,
            PixelFormat::YUV422P9LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P9LE,
            PixelFormat::GBRP => ffi::AVPixelFormat::AV_PIX_FMT_GBRP,
            PixelFormat::GBRP9BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP9BE,
            PixelFormat::GBRP9LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP9LE,
            PixelFormat::GBRP10BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP10BE,
            PixelFormat::GBRP10LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP10LE,
            PixelFormat::GBRP16BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP16BE,
            PixelFormat::GBRP16LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP16LE,
            PixelFormat::YUVA420P9BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P9BE,
            PixelFormat::YUVA420P9LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P9LE,
            PixelFormat::YUVA422P9BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P9BE,
            PixelFormat::YUVA422P9LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P9LE,
            PixelFormat::YUVA444P9BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P9BE,
            PixelFormat::YUVA444P9LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P9LE,
            PixelFormat::YUVA420P10BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P10BE,
            PixelFormat::YUVA420P10LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P10LE,
            PixelFormat::YUVA422P10BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P10BE,
            PixelFormat::YUVA422P10LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P10LE,
            PixelFormat::YUVA444P10BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P10BE,
            PixelFormat::YUVA444P10LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P10LE,
            PixelFormat::YUVA420P16BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P16BE,
            PixelFormat::YUVA420P16LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA420P16LE,
            PixelFormat::YUVA422P16BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P16BE,
            PixelFormat::YUVA422P16LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P16LE,
            PixelFormat::YUVA444P16BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P16BE,
            PixelFormat::YUVA444P16LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P16LE,
            PixelFormat::VDPAU => ffi::AVPixelFormat::AV_PIX_FMT_VDPAU,
            PixelFormat::XYZ12LE => ffi::AVPixelFormat::AV_PIX_FMT_XYZ12LE,
            PixelFormat::XYZ12BE => ffi::AVPixelFormat::AV_PIX_FMT_XYZ12BE,
            PixelFormat::NV16 => ffi::AVPixelFormat::AV_PIX_FMT_NV16,
            PixelFormat::NV20LE => ffi::AVPixelFormat::AV_PIX_FMT_NV20LE,
            PixelFormat::NV20BE => ffi::AVPixelFormat::AV_PIX_FMT_NV20BE,
            PixelFormat::RGBA64BE => ffi::AVPixelFormat::AV_PIX_FMT_RGBA64BE,
            PixelFormat::RGBA64LE => ffi::AVPixelFormat::AV_PIX_FMT_RGBA64LE,
            PixelFormat::BGRA64BE => ffi::AVPixelFormat::AV_PIX_FMT_BGRA64BE,
            PixelFormat::BGRA64LE => ffi::AVPixelFormat::AV_PIX_FMT_BGRA64LE,
            PixelFormat::YVYU422 => ffi::AVPixelFormat::AV_PIX_FMT_YVYU422,
            PixelFormat::YA16BE => ffi::AVPixelFormat::AV_PIX_FMT_YA16BE,
            PixelFormat::YA16LE => ffi::AVPixelFormat::AV_PIX_FMT_YA16LE,
            PixelFormat::QSV => ffi::AVPixelFormat::AV_PIX_FMT_QSV,
            PixelFormat::MMAL => ffi::AVPixelFormat::AV_PIX_FMT_MMAL,
            PixelFormat::D3D11VA_VLD => ffi::AVPixelFormat::AV_PIX_FMT_D3D11VA_VLD,
            PixelFormat::CUDA => ffi::AVPixelFormat::AV_PIX_FMT_CUDA,
            PixelFormat::ZRGB => ffi::AVPixelFormat::AV_PIX_FMT_0RGB,
            PixelFormat::RGBZ => ffi::AVPixelFormat::AV_PIX_FMT_RGB0,
            PixelFormat::ZBGR => ffi::AVPixelFormat::AV_PIX_FMT_0BGR,
            PixelFormat::BGRZ => ffi::AVPixelFormat::AV_PIX_FMT_BGR0,
            PixelFormat::YUVA444P => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P,
            PixelFormat::YUVA422P => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P,
            PixelFormat::YUV420P12BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P12BE,
            PixelFormat::YUV420P12LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P12LE,
            PixelFormat::YUV420P14BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P14BE,
            PixelFormat::YUV420P14LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV420P14LE,
            PixelFormat::YUV422P12BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P12BE,
            PixelFormat::YUV422P12LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P12LE,
            PixelFormat::YUV422P14BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P14BE,
            PixelFormat::YUV422P14LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV422P14LE,
            PixelFormat::YUV444P12BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P12BE,
            PixelFormat::YUV444P12LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P12LE,
            PixelFormat::YUV444P14BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P14BE,
            PixelFormat::YUV444P14LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV444P14LE,
            PixelFormat::GBRP12BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP12BE,
            PixelFormat::GBRP12LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP12LE,
            PixelFormat::GBRP14BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP14BE,
            PixelFormat::GBRP14LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRP14LE,
            PixelFormat::GBRAP => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP,
            PixelFormat::GBRAP16BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP16BE,
            PixelFormat::GBRAP16LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP16LE,
            PixelFormat::YUVJ411P => ffi::AVPixelFormat::AV_PIX_FMT_YUVJ411P,
            PixelFormat::BAYER_BGGR8 => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_BGGR8,
            PixelFormat::BAYER_RGGB8 => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_RGGB8,
            PixelFormat::BAYER_GBRG8 => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GBRG8,
            PixelFormat::BAYER_GRBG8 => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GRBG8,
            PixelFormat::BAYER_BGGR16LE => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_BGGR16LE,
            PixelFormat::BAYER_BGGR16BE => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_BGGR16BE,
            PixelFormat::BAYER_RGGB16LE => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_RGGB16LE,
            PixelFormat::BAYER_RGGB16BE => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_RGGB16BE,
            PixelFormat::BAYER_GBRG16LE => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GBRG16LE,
            PixelFormat::BAYER_GBRG16BE => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GBRG16BE,
            PixelFormat::BAYER_GRBG16LE => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GRBG16LE,
            PixelFormat::BAYER_GRBG16BE => ffi::AVPixelFormat::AV_PIX_FMT_BAYER_GRBG16BE,
            PixelFormat::YUV440P10LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV440P10LE,
            PixelFormat::YUV440P10BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV440P10BE,
            PixelFormat::YUV440P12LE => ffi::AVPixelFormat::AV_PIX_FMT_YUV440P12LE,
            PixelFormat::YUV440P12BE => ffi::AVPixelFormat::AV_PIX_FMT_YUV440P12BE,
            PixelFormat::AYUV64LE => ffi::AVPixelFormat::AV_PIX_FMT_AYUV64LE,
            PixelFormat::AYUV64BE => ffi::AVPixelFormat::AV_PIX_FMT_AYUV64BE,
            PixelFormat::VIDEOTOOLBOX => ffi::AVPixelFormat::AV_PIX_FMT_VIDEOTOOLBOX,
            PixelFormat::RGB32 => ffi::AV_PIX_FMT_RGB32,
            PixelFormat::RGB32_1 => ffi::AV_PIX_FMT_RGB32_1,
            PixelFormat::BGR32 => ffi::AV_PIX_FMT_BGR32,
            PixelFormat::BGR32_1 => ffi::AV_PIX_FMT_BGR32_1,
            PixelFormat::ZRGB32 => ffi::AV_PIX_FMT_0RGB32,
            PixelFormat::ZBGR32 => ffi::AV_PIX_FMT_0BGR32,
            PixelFormat::GRAY16 => ffi::AV_PIX_FMT_GRAY16,
            PixelFormat::YA16 => ffi::AV_PIX_FMT_YA16,
            PixelFormat::RGB48 => ffi::AV_PIX_FMT_RGB48,
            PixelFormat::RGB565 => ffi::AV_PIX_FMT_RGB565,
            PixelFormat::RGB555 => ffi::AV_PIX_FMT_RGB555,
            PixelFormat::RGB444 => ffi::AV_PIX_FMT_RGB444,
            PixelFormat::BGR48 => ffi::AV_PIX_FMT_BGR48,
            PixelFormat::BGR565 => ffi::AV_PIX_FMT_BGR565,
            PixelFormat::BGR555 => ffi::AV_PIX_FMT_BGR555,
            PixelFormat::BGR444 => ffi::AV_PIX_FMT_BGR444,
            PixelFormat::YUV420P9 => ffi::AV_PIX_FMT_YUV420P9,
            PixelFormat::YUV422P9 => ffi::AV_PIX_FMT_YUV422P9,
            PixelFormat::YUV444P9 => ffi::AV_PIX_FMT_YUV444P9,
            PixelFormat::YUV420P10 => ffi::AV_PIX_FMT_YUV420P10,
            PixelFormat::YUV422P10 => ffi::AV_PIX_FMT_YUV422P10,
            PixelFormat::YUV440P10 => ffi::AV_PIX_FMT_YUV440P10,
            PixelFormat::YUV444P10 => ffi::AV_PIX_FMT_YUV444P10,
            PixelFormat::YUV420P12 => ffi::AV_PIX_FMT_YUV420P12,
            PixelFormat::YUV422P12 => ffi::AV_PIX_FMT_YUV422P12,
            PixelFormat::YUV440P12 => ffi::AV_PIX_FMT_YUV440P12,
            PixelFormat::YUV444P12 => ffi::AV_PIX_FMT_YUV444P12,
            PixelFormat::YUV420P14 => ffi::AV_PIX_FMT_YUV420P14,
            PixelFormat::YUV422P14 => ffi::AV_PIX_FMT_YUV422P14,
            PixelFormat::YUV444P14 => ffi::AV_PIX_FMT_YUV444P14,
            PixelFormat::YUV420P16 => ffi::AV_PIX_FMT_YUV420P16,
            PixelFormat::YUV422P16 => ffi::AV_PIX_FMT_YUV422P16,
            PixelFormat::YUV444P16 => ffi::AV_PIX_FMT_YUV444P16,
            PixelFormat::GBRP9 => ffi::AV_PIX_FMT_GBRP9,
            PixelFormat::GBRP10 => ffi::AV_PIX_FMT_GBRP10,
            PixelFormat::GBRP12 => ffi::AV_PIX_FMT_GBRP12,
            PixelFormat::GBRP14 => ffi::AV_PIX_FMT_GBRP14,
            PixelFormat::GBRP16 => ffi::AV_PIX_FMT_GBRP16,
            PixelFormat::GBRAP16 => ffi::AV_PIX_FMT_GBRAP16,
            PixelFormat::BAYER_BGGR16 => ffi::AV_PIX_FMT_BAYER_BGGR16,
            PixelFormat::BAYER_RGGB16 => ffi::AV_PIX_FMT_BAYER_RGGB16,
            PixelFormat::BAYER_GBRG16 => ffi::AV_PIX_FMT_BAYER_GBRG16,
            PixelFormat::BAYER_GRBG16 => ffi::AV_PIX_FMT_BAYER_GRBG16,
            PixelFormat::YUVA420P9 => ffi::AV_PIX_FMT_YUVA420P9,
            PixelFormat::YUVA422P9 => ffi::AV_PIX_FMT_YUVA422P9,
            PixelFormat::YUVA444P9 => ffi::AV_PIX_FMT_YUVA444P9,
            PixelFormat::YUVA420P10 => ffi::AV_PIX_FMT_YUVA420P10,
            PixelFormat::YUVA422P10 => ffi::AV_PIX_FMT_YUVA422P10,
            PixelFormat::YUVA444P10 => ffi::AV_PIX_FMT_YUVA444P10,
            PixelFormat::YUVA420P16 => ffi::AV_PIX_FMT_YUVA420P16,
            PixelFormat::YUVA422P16 => ffi::AV_PIX_FMT_YUVA422P16,
            PixelFormat::YUVA444P16 => ffi::AV_PIX_FMT_YUVA444P16,
            PixelFormat::XYZ12 => ffi::AV_PIX_FMT_XYZ12,
            PixelFormat::NV20 => ffi::AV_PIX_FMT_NV20,
            PixelFormat::AYUV64 => ffi::AV_PIX_FMT_AYUV64,
            PixelFormat::P010LE => ffi::AVPixelFormat::AV_PIX_FMT_P010LE,
            PixelFormat::P010BE => ffi::AVPixelFormat::AV_PIX_FMT_P010BE,
            PixelFormat::GBRAP12BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP12BE,
            PixelFormat::GBRAP12LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP12LE,
            PixelFormat::GBRAP10LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP10LE,
            PixelFormat::GBRAP10BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP10BE,
            PixelFormat::MEDIACODEC => ffi::AVPixelFormat::AV_PIX_FMT_MEDIACODEC,
            PixelFormat::GRAY12BE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY12BE,
            PixelFormat::GRAY12LE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY12LE,
            PixelFormat::GRAY10BE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY10BE,
            PixelFormat::GRAY10LE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY10LE,
            PixelFormat::P016LE => ffi::AVPixelFormat::AV_PIX_FMT_P016LE,
            PixelFormat::P016BE => ffi::AVPixelFormat::AV_PIX_FMT_P016BE,
            PixelFormat::D3D11 => ffi::AVPixelFormat::AV_PIX_FMT_D3D11,
            PixelFormat::GRAY9BE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY9BE,
            PixelFormat::GRAY9LE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY9LE,
            PixelFormat::GBRPF32BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRPF32BE,
            PixelFormat::GBRPF32LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRPF32LE,
            PixelFormat::GBRAPF32BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAPF32BE,
            PixelFormat::GBRAPF32LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAPF32LE,
            PixelFormat::DRM_PRIME => ffi::AVPixelFormat::AV_PIX_FMT_DRM_PRIME,
            PixelFormat::OPENCL => ffi::AVPixelFormat::AV_PIX_FMT_OPENCL,
            PixelFormat::GRAY14BE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY14BE,
            PixelFormat::GRAY14LE => ffi::AVPixelFormat::AV_PIX_FMT_GRAY14LE,
            PixelFormat::GRAYF32BE => ffi::AVPixelFormat::AV_PIX_FMT_GRAYF32BE,
            PixelFormat::GRAYF32LE => ffi::AVPixelFormat::AV_PIX_FMT_GRAYF32LE,
            PixelFormat::YUVA422P12BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P12BE,
            PixelFormat::YUVA422P12LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA422P12LE,
            PixelFormat::YUVA444P12BE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P12BE,
            PixelFormat::YUVA444P12LE => ffi::AVPixelFormat::AV_PIX_FMT_YUVA444P12LE,
            PixelFormat::NV24 => ffi::AVPixelFormat::AV_PIX_FMT_NV24,
            PixelFormat::NV42 => ffi::AVPixelFormat::AV_PIX_FMT_NV42,
            PixelFormat::VULKAN => ffi::AVPixelFormat::AV_PIX_FMT_VULKAN,
            PixelFormat::Y210BE => ffi::AVPixelFormat::AV_PIX_FMT_Y210BE,
            PixelFormat::Y210LE => ffi::AVPixelFormat::AV_PIX_FMT_Y210LE,
            PixelFormat::X2RGB10LE => ffi::AVPixelFormat::AV_PIX_FMT_X2RGB10LE,
            PixelFormat::X2RGB10BE => ffi::AVPixelFormat::AV_PIX_FMT_X2RGB10BE,
            PixelFormat::X2BGR10LE => ffi::AVPixelFormat::AV_PIX_FMT_X2BGR10LE,
            PixelFormat::X2BGR10BE => ffi::AVPixelFormat::AV_PIX_FMT_X2BGR10BE,
            PixelFormat::P210BE => ffi::AVPixelFormat::AV_PIX_FMT_P210BE,
            PixelFormat::P210LE => ffi::AVPixelFormat::AV_PIX_FMT_P210LE,
            PixelFormat::P410BE => ffi::AVPixelFormat::AV_PIX_FMT_P410BE,
            PixelFormat::P410LE => ffi::AVPixelFormat::AV_PIX_FMT_P410LE,
            PixelFormat::P216BE => ffi::AVPixelFormat::AV_PIX_FMT_P216BE,
            PixelFormat::P216LE => ffi::AVPixelFormat::AV_PIX_FMT_P216LE,
            PixelFormat::P416BE => ffi::AVPixelFormat::AV_PIX_FMT_P416BE,
            PixelFormat::P416LE => ffi::AVPixelFormat::AV_PIX_FMT_P416LE,
            PixelFormat::VUYA => ffi::AVPixelFormat::AV_PIX_FMT_VUYA,
            PixelFormat::RGBAF16BE => ffi::AVPixelFormat::AV_PIX_FMT_RGBAF16BE,
            PixelFormat::RGBAF16LE => ffi::AVPixelFormat::AV_PIX_FMT_RGBAF16LE,
            PixelFormat::VUYX => ffi::AVPixelFormat::AV_PIX_FMT_VUYX,
            PixelFormat::P012LE => ffi::AVPixelFormat::AV_PIX_FMT_P012LE,
            PixelFormat::P012BE => ffi::AVPixelFormat::AV_PIX_FMT_P012BE,
            PixelFormat::Y212BE => ffi::AVPixelFormat::AV_PIX_FMT_Y212BE,
            PixelFormat::Y212LE => ffi::AVPixelFormat::AV_PIX_FMT_Y212LE,
            PixelFormat::XV30BE => ffi::AVPixelFormat::AV_PIX_FMT_XV30BE,
            PixelFormat::XV30LE => ffi::AVPixelFormat::AV_PIX_FMT_XV30LE,
            PixelFormat::XV36BE => ffi::AVPixelFormat::AV_PIX_FMT_XV36BE,
            PixelFormat::XV36LE => ffi::AVPixelFormat::AV_PIX_FMT_XV36LE,
            PixelFormat::RGBF32BE => ffi::AVPixelFormat::AV_PIX_FMT_RGBF32BE,
            PixelFormat::RGBF32LE => ffi::AVPixelFormat::AV_PIX_FMT_RGBF32LE,
            PixelFormat::RGBAF32BE => ffi::AVPixelFormat::AV_PIX_FMT_RGBAF32BE,
            PixelFormat::RGBAF32LE => ffi::AVPixelFormat::AV_PIX_FMT_RGBAF32LE,
            PixelFormat::P212BE => ffi::AVPixelFormat::AV_PIX_FMT_P212BE,
            PixelFormat::P212LE => ffi::AVPixelFormat::AV_PIX_FMT_P212LE,
            PixelFormat::P412BE => ffi::AVPixelFormat::AV_PIX_FMT_P412BE,
            PixelFormat::P412LE => ffi::AVPixelFormat::AV_PIX_FMT_P412LE,
            PixelFormat::GBRAP14BE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP14BE,
            PixelFormat::GBRAP14LE => ffi::AVPixelFormat::AV_PIX_FMT_GBRAP14LE,
            PixelFormat::D3D12 => ffi::AVPixelFormat::AV_PIX_FMT_D3D12,
        }
    }
}

impl PixelFormat {
    pub const Y400A: PixelFormat = PixelFormat::YA8;
    pub const GRAY8A: PixelFormat = PixelFormat::YA8;
    pub const GBR24P: PixelFormat = PixelFormat::GBRP;

    pub fn descriptor(self) -> Option<PixelDescriptor> {
        unsafe {
            let ptr = ffi::av_pix_fmt_desc_get(self.into());
            ptr.as_ref().map(|ptr| PixelDescriptor(ptr))
        }
    }
}

#[derive(Debug)]
pub enum ParsePixelError {
    NulError(std::ffi::NulError),
    UnknownFormat,
}

impl std::fmt::Display for ParsePixelError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match *self {
            ParsePixelError::NulError(ref e) => e.fmt(f),
            ParsePixelError::UnknownFormat => write!(f, "unknown pixel format"),
        }
    }
}

impl std::error::Error for ParsePixelError {
    fn cause(&self) -> Option<&dyn std::error::Error> {
        match *self {
            ParsePixelError::NulError(ref e) => Some(e),
            ParsePixelError::UnknownFormat => None,
        }
    }
}

impl From<std::ffi::NulError> for ParsePixelError {
    fn from(x: std::ffi::NulError) -> ParsePixelError {
        ParsePixelError::NulError(x)
    }
}

impl FromStr for PixelFormat {
    type Err = ParsePixelError;

    #[inline(always)]
    fn from_str(s: &str) -> Result<PixelFormat, ParsePixelError> {
        let cstring = std::ffi::CString::new(s)?;
        let format = unsafe { ffi::av_get_pix_fmt(cstring.as_ptr()) }.into();

        if format == PixelFormat::None {
            Err(ParsePixelError::UnknownFormat)
        } else {
            Ok(format)
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub struct PixelDescriptor(*const ffi::AVPixFmtDescriptor);

unsafe impl Send for PixelDescriptor {}
unsafe impl Sync for PixelDescriptor {}

impl PixelDescriptor {
    #[inline]
    pub(crate) unsafe fn as_ptr(&self) -> *const ffi::AVPixFmtDescriptor {
        self.0
    }

    #[inline]
    pub fn name(&self) -> &str {
        unsafe {
            let ptr = (*self.0).name;
            let cstr = std::ffi::CStr::from_ptr(ptr);
            std::str::from_utf8_unchecked(cstr.to_bytes())
        }
    }

    #[inline]
    pub fn nb_components(&self) -> u8 {
        unsafe { (*self.as_ptr()).nb_components }
    }

    #[inline]
    pub fn log2_chroma_w(&self) -> u8 {
        unsafe { (*self.as_ptr()).log2_chroma_w }
    }

    #[inline]
    pub fn log2_chroma_h(&self) -> u8 {
        unsafe { (*self.as_ptr()).log2_chroma_h }
    }
}
